use super::hir::{typed_hir_from_c, HirBinding, HirFunction, HirType, TypedHir};
use super::identifiers::{identifier_map, IdentifierTarget};
use super::{
    ArrayInitProvenance, AssignmentProvenance, Expr, ExprStmtProvenance, Func, FunctionOrigin,
    IfOrigin, LValue, LoopKind, Stmt, TranslateError,
};
use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

pub(super) fn translate(source: &str) -> Result<String, TranslateError> {
    let hir = typed_hir_from_c(source)?;
    Emitter::new(&hir)?.emit()
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum ValueKind {
    I32,
    Bool,
}

struct Emitter<'a> {
    hir: &'a TypedHir,
    signatures: HashMap<String, usize>,
    function_names: HashMap<String, String>,
    binding_names: HashMap<String, String>,
    out: String,
    loop_depth: usize,
    active_range_iterators: HashSet<String>,
    promoted_range_iterators: HashSet<String>,
}

impl<'a> Emitter<'a> {
    fn new(hir: &'a TypedHir) -> Result<Self, TranslateError> {
        let mut signatures = HashMap::new();
        for function in &hir.ast.funcs {
            if signatures
                .insert(function.name.clone(), function.params.len())
                .is_some()
            {
                return Err(TranslateError::new(
                    function.line,
                    format!("function '{}' is defined twice", function.name),
                ));
            }
        }
        Ok(Self {
            hir,
            signatures,
            function_names: identifier_map(
                hir.ast.funcs.iter().map(|function| function.name.as_str()),
                IdentifierTarget::Rust,
            ),
            binding_names: HashMap::new(),
            out: String::new(),
            loop_depth: 0,
            active_range_iterators: HashSet::new(),
            promoted_range_iterators: HashSet::new(),
        })
    }

    fn emit(mut self) -> Result<String, TranslateError> {
        self.out
            .push_str("// Generated by the StudyRISC-V C-to-Rust translator.\n");
        self.out
            .push_str("// Compilable within the documented safe integer subset.\n\n");
        for (index, function) in self.hir.ast.funcs.iter().enumerate() {
            if function.origin != FunctionOrigin::Explicit {
                return Err(TranslateError::new(
                    function.line,
                    "C-to-Rust requires explicit function definitions; loose top-level statements are not supported",
                ));
            }
            if index > 0 {
                self.out.push('\n');
            }
            self.emit_function(function)?;
        }
        Ok(self.out)
    }

    fn emit_function(&mut self, function: &Func) -> Result<(), TranslateError> {
        self.loop_depth = 0;
        self.active_range_iterators.clear();
        self.promoted_range_iterators.clear();
        let function_hir = self.function_hir(&function.name);
        if function_hir.return_type != HirType::I32 {
            return Err(TranslateError::new(
                function.line,
                "C-to-Rust supports only int-returning C functions",
            ));
        }
        let mut bindings = HashSet::new();
        for binding in &function_hir.bindings {
            if !bindings.insert(&binding.name) {
                return Err(TranslateError::new(
                    binding.line,
                    format!("binding '{}' is declared twice", binding.name),
                ));
            }
        }
        self.binding_names = identifier_map(
            function_hir
                .bindings
                .iter()
                .map(|binding| binding.name.as_str()),
            IdentifierTarget::Rust,
        );
        let parameters = function
            .params
            .iter()
            .map(|name| {
                let binding = self.binding(function, name, function.line)?;
                let mutable = if binding.mutable { "mut " } else { "" };
                Ok(format!("{mutable}{}: i32", self.binding_name(name)))
            })
            .collect::<Result<Vec<_>, TranslateError>>()?
            .join(", ");
        let function_name = self.function_name(&function.name);
        let _ = writeln!(self.out, "fn {function_name}({parameters}) -> i32 {{");
        self.emit_statements(function, &function.body, 1)?;
        if !statements_always_return(&function.body) {
            return Err(TranslateError::new(
                function.line,
                format!(
                    "function '{}' can fall through without returning an int value",
                    function.name
                ),
            ));
        }
        self.out.push_str("}\n");
        Ok(())
    }

    fn emit_statements(
        &mut self,
        function: &Func,
        statements: &[Stmt],
        depth: usize,
    ) -> Result<(), TranslateError> {
        for statement in statements {
            self.emit_statement(function, statement, depth)?;
        }
        Ok(())
    }

    fn emit_statement(
        &mut self,
        function: &Func,
        statement: &Stmt,
        depth: usize,
    ) -> Result<(), TranslateError> {
        let indent = "    ".repeat(depth);
        match statement {
            Stmt::Decl(name, initial, _, line) => {
                let initial = initial.as_ref().ok_or_else(|| {
                    TranslateError::new(
                        *line,
                        format!("uninitialized local '{name}' cannot be represented in safe Rust"),
                    )
                })?;
                let value = self.i32_value(function, initial, "local initializer")?;
                let mutable = if self.binding(function, name, *line)?.mutable {
                    "mut "
                } else {
                    ""
                };
                let name = self.binding_name(name);
                let _ = writeln!(self.out, "{indent}let {mutable}{name}: i32 = {value};");
            }
            Stmt::DeclArray(name, size, initial, source, initializer, line) => {
                if !source.initialized || *initializer == ArrayInitProvenance::Absent {
                    return Err(TranslateError::new(
                        *line,
                        format!("uninitialized array '{name}' cannot be represented in safe Rust"),
                    ));
                }
                let mut values = initial
                    .iter()
                    .map(|value| self.i32_value(function, value, "array initializer"))
                    .collect::<Result<Vec<_>, _>>()?;
                values.resize(*size, "0".to_string());
                let mutable = if self.binding(function, name, *line)?.mutable {
                    "mut "
                } else {
                    ""
                };
                let name = self.binding_name(name);
                let _ = writeln!(
                    self.out,
                    "{indent}let {mutable}{name}: [i32; {size}] = [{}];",
                    values.join(", ")
                );
            }
            Stmt::Expr(_, ExprStmtProvenance::Empty) => {}
            Stmt::Expr(expression, ExprStmtProvenance::Expression) => {
                if matches!(expression, Expr::Assign(..)) {
                    let assignment = self.assignment_statement(function, expression)?;
                    let _ = writeln!(self.out, "{indent}{assignment};");
                } else {
                    let (value, _) = self.value(function, expression)?;
                    let _ = writeln!(self.out, "{indent}{value};");
                }
            }
            Stmt::If(_, body, _, source) if source.origin == IfOrigin::PlainBlock => {
                let _ = writeln!(self.out, "{indent}{{");
                self.emit_statements(function, body, depth + 1)?;
                let _ = writeln!(self.out, "{indent}}}");
            }
            Stmt::If(condition, body, otherwise, _) => {
                let condition = self.condition(function, condition)?;
                let _ = writeln!(self.out, "{indent}if {condition} {{");
                self.emit_statements(function, body, depth + 1)?;
                if otherwise.is_empty() {
                    let _ = writeln!(self.out, "{indent}}}");
                } else {
                    let _ = writeln!(self.out, "{indent}}} else {{");
                    self.emit_statements(function, otherwise, depth + 1)?;
                    let _ = writeln!(self.out, "{indent}}}");
                }
            }
            Stmt::While(condition, body, source) => {
                if source.kind != LoopKind::While {
                    return Err(TranslateError::new(
                        source.line,
                        "internal: C AST contains a non-while loop in a while statement",
                    ));
                }
                let condition = self.condition(function, condition)?;
                let _ = writeln!(self.out, "{indent}while {condition} {{");
                self.loop_depth += 1;
                let result = self.emit_statements(function, body, depth + 1);
                self.loop_depth -= 1;
                result?;
                let _ = writeln!(self.out, "{indent}}}");
            }
            Stmt::For(initial, condition, post, body, source) => {
                if source.kind != LoopKind::CFor {
                    return Err(TranslateError::new(
                        source.line,
                        "internal: C AST contains a non-C for loop",
                    ));
                }
                let loop_parts = canonical_range(initial, condition, post, source.line)?;
                self.validate_range(function, body, &loop_parts)?;
                let start = self.i32_value(function, loop_parts.start, "range start")?;
                let end = self.i32_value(function, loop_parts.end, "range bound")?;
                self.promoted_range_iterators
                    .insert(loop_parts.iterator.to_string());
                self.active_range_iterators
                    .insert(loop_parts.iterator.to_string());
                let _ = writeln!(
                    self.out,
                    "{indent}for {} in {start}..{end} {{",
                    self.binding_name(loop_parts.iterator)
                );
                self.loop_depth += 1;
                let result = self.emit_statements(function, body, depth + 1);
                self.loop_depth -= 1;
                self.active_range_iterators.remove(loop_parts.iterator);
                result?;
                let _ = writeln!(self.out, "{indent}}}");
            }
            Stmt::Return(value, _, line) => {
                let value = value.as_ref().ok_or_else(|| {
                    TranslateError::new(
                        *line,
                        "bare return in an int function cannot be represented in safe Rust",
                    )
                })?;
                let value = self.i32_value(function, value, "return value")?;
                let _ = writeln!(self.out, "{indent}return {value};");
            }
            Stmt::Break(line) => {
                if self.loop_depth == 0 {
                    return Err(TranslateError::new(*line, "break outside a loop"));
                }
                let _ = writeln!(self.out, "{indent}break;");
            }
            Stmt::Continue(line) => {
                if self.loop_depth == 0 {
                    return Err(TranslateError::new(*line, "continue outside a loop"));
                }
                let _ = writeln!(self.out, "{indent}continue;");
            }
        }
        Ok(())
    }

    fn value(
        &self,
        function: &Func,
        expression: &Expr,
    ) -> Result<(String, ValueKind), TranslateError> {
        let line = expression_line(expression);
        match expression {
            Expr::Num(value, _, _) => Ok((value.to_string(), ValueKind::I32)),
            Expr::Var(name, line) => {
                self.scalar_binding(function, name, *line)?;
                self.reject_escaped_iterator(name, *line)?;
                Ok((self.binding_name(name), ValueKind::I32))
            }
            Expr::Index(name, index, line) => {
                self.array_binding(function, name, *line)?;
                let index = self.array_index(function, index)?;
                Ok((
                    format!("{}[{index}]", self.binding_name(name)),
                    ValueKind::I32,
                ))
            }
            Expr::Unary("!", value, _) => {
                let condition = self.condition(function, value)?;
                Ok((format!("(!{condition})"), ValueKind::Bool))
            }
            Expr::Unary("~", value, _) => {
                let value = self.i32_value(function, value, "bitwise-not operand")?;
                Ok((format!("(!{value})"), ValueKind::I32))
            }
            Expr::Unary("-", value, _) => {
                let value = self.i32_value(function, value, "negation operand")?;
                Ok((format!("(-{value})"), ValueKind::I32))
            }
            Expr::Unary(_, _, _) => Err(TranslateError::new(
                line,
                "unsupported unary expression in C-to-Rust translation",
            )),
            Expr::Binary("&&", left, right, _) => Ok((
                format!(
                    "({} && {})",
                    self.condition(function, left)?,
                    self.condition(function, right)?
                ),
                ValueKind::Bool,
            )),
            Expr::Binary("||", left, right, _) => Ok((
                format!(
                    "({} || {})",
                    self.condition(function, left)?,
                    self.condition(function, right)?
                ),
                ValueKind::Bool,
            )),
            Expr::Binary(operator @ ("==" | "!=" | "<" | "<=" | ">" | ">="), left, right, _) => {
                let left = self.i32_value(function, left, "comparison operand")?;
                let right = self.i32_value(function, right, "comparison operand")?;
                Ok((format!("({left} {operator} {right})"), ValueKind::Bool))
            }
            Expr::Binary(operator, left, right, _) => {
                let left = self.i32_value(function, left, "arithmetic operand")?;
                let right = self.i32_value(function, right, "arithmetic operand")?;
                Ok((format!("({left} {operator} {right})"), ValueKind::I32))
            }
            Expr::Assign(_, _, _, _) => Err(TranslateError::new(
                line,
                "value-producing assignment cannot be represented in the safe Rust subset; use assignment as its own statement",
            )),
            Expr::Call(name, arguments, line) => {
                let arity = self.signatures.get(name).ok_or_else(|| {
                    TranslateError::new(*line, format!("call to undefined function '{name}'"))
                })?;
                if arguments.len() != *arity {
                    return Err(TranslateError::new(
                        *line,
                        format!(
                            "function '{name}' expects {arity} arguments, found {}",
                            arguments.len()
                        ),
                    ));
                }
                let arguments = arguments
                    .iter()
                    .map(|argument| self.i32_value(function, argument, "function argument"))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ");
                Ok((
                    format!("{}({arguments})", self.function_name(name)),
                    ValueKind::I32,
                ))
            }
        }
    }

    fn i32_value(
        &self,
        function: &Func,
        expression: &Expr,
        context: &str,
    ) -> Result<String, TranslateError> {
        let (value, kind) = self.value(function, expression)?;
        if kind == ValueKind::I32 {
            Ok(value)
        } else {
            Err(TranslateError::new(
                expression_line(expression),
                format!(
                    "comparison or logical result used as an integer {context} cannot be represented in the safe Rust subset"
                ),
            ))
        }
    }

    fn condition(&self, function: &Func, expression: &Expr) -> Result<String, TranslateError> {
        let (value, kind) = self.value(function, expression)?;
        Ok(if kind == ValueKind::Bool {
            value
        } else {
            format!("({value} != 0)")
        })
    }

    fn assignment_statement(
        &self,
        function: &Func,
        expression: &Expr,
    ) -> Result<String, TranslateError> {
        let Expr::Assign(target, value, source, line) = expression else {
            return Err(TranslateError::new(
                expression_line(expression),
                "internal: expected assignment statement",
            ));
        };
        let target = self.lvalue(function, target)?;
        let value = self.i32_value(function, value, "assignment value")?;
        let assignment = match source {
            AssignmentProvenance::Simple => format!("{target} = {value}"),
            AssignmentProvenance::Compound(operator) => {
                format!("{target} {operator}= {value}")
            }
            AssignmentProvenance::PrefixIncrement | AssignmentProvenance::PostfixIncrement => {
                format!("{target} += 1")
            }
            AssignmentProvenance::PrefixDecrement | AssignmentProvenance::PostfixDecrement => {
                format!("{target} -= 1")
            }
        };
        let _ = line;
        Ok(assignment)
    }

    fn lvalue(&self, function: &Func, target: &LValue) -> Result<String, TranslateError> {
        match target {
            LValue::Var(name, line) => {
                let binding = self.scalar_binding(function, name, *line)?;
                if !binding.mutable {
                    return Err(TranslateError::new(
                        *line,
                        format!("assignment target '{name}' was not inferred mutable"),
                    ));
                }
                self.reject_escaped_iterator(name, *line)?;
                Ok(self.binding_name(name))
            }
            LValue::Index(name, index, line) => {
                let binding = self.array_binding(function, name, *line)?;
                if !binding.mutable {
                    return Err(TranslateError::new(
                        *line,
                        format!("assignment target array '{name}' was not inferred mutable"),
                    ));
                }
                Ok(format!(
                    "{}[{}]",
                    self.binding_name(name),
                    self.array_index(function, index)?
                ))
            }
        }
    }

    fn array_index(&self, function: &Func, index: &Expr) -> Result<String, TranslateError> {
        match index {
            Expr::Num(value, _, _) if *value >= 0 => Ok(value.to_string()),
            Expr::Var(name, line) if self.active_range_iterators.contains(name) => {
                self.scalar_binding(function, name, *line)?;
                Ok(name.clone())
            }
            _ => Err(TranslateError::new(
                expression_line(index),
                "arbitrary i32 array indexes cannot be represented without a checked usize conversion; use a nonnegative literal or the active canonical range iterator",
            )),
        }
    }

    fn validate_range(
        &self,
        function: &Func,
        body: &[Stmt],
        range: &CanonicalRange<'_>,
    ) -> Result<(), TranslateError> {
        if expression_has_side_effect(range.start) {
            return Err(TranslateError::new(
                expression_line(range.start),
                "canonical C range start must be side-effect free",
            ));
        }
        if expression_has_side_effect(range.end) {
            return Err(TranslateError::new(
                expression_line(range.end),
                "canonical C range bound must be side-effect free",
            ));
        }
        let mut referenced = HashSet::new();
        collect_variables(range.end, &mut referenced);
        if referenced.contains(range.iterator) {
            return Err(TranslateError::new(
                range.line,
                "canonical C range bound cannot reference its iterator",
            ));
        }
        for name in referenced {
            let binding = self.binding(function, &name, expression_line(range.end))?;
            if binding.mutable {
                return Err(TranslateError::new(
                    expression_line(range.end),
                    format!(
                        "canonical C range bound references mutable binding '{name}'; Rust range bounds are snapshotted once"
                    ),
                ));
            }
        }
        if statements_assign_to(body, range.iterator) {
            return Err(TranslateError::new(
                range.line,
                format!(
                    "canonical C range iterator '{}' is modified inside the loop body",
                    range.iterator
                ),
            ));
        }
        Ok(())
    }

    fn reject_escaped_iterator(&self, name: &str, line: usize) -> Result<(), TranslateError> {
        if self.promoted_range_iterators.contains(name)
            && !self.active_range_iterators.contains(name)
        {
            Err(TranslateError::new(
                line,
                format!(
                    "canonical range iterator '{name}' is used outside its loop and cannot be scoped equivalently in Rust"
                ),
            ))
        } else {
            Ok(())
        }
    }

    fn scalar_binding(
        &self,
        function: &Func,
        name: &str,
        line: usize,
    ) -> Result<&HirBinding, TranslateError> {
        let binding = self.binding(function, name, line)?;
        if binding.array_len.is_some() {
            return Err(TranslateError::new(
                line,
                format!("'{name}' is an array and can only be used with an index"),
            ));
        }
        Ok(binding)
    }

    fn array_binding(
        &self,
        function: &Func,
        name: &str,
        line: usize,
    ) -> Result<&HirBinding, TranslateError> {
        let binding = self.binding(function, name, line)?;
        if binding.array_len.is_none() {
            return Err(TranslateError::new(
                line,
                format!("'{name}' is not an array"),
            ));
        }
        Ok(binding)
    }

    fn binding(
        &self,
        function: &Func,
        name: &str,
        line: usize,
    ) -> Result<&HirBinding, TranslateError> {
        self.function_hir(&function.name)
            .bindings
            .iter()
            .find(|binding| binding.name == name)
            .ok_or_else(|| TranslateError::new(line, format!("binding '{name}' is not declared")))
    }

    fn function_hir(&self, name: &str) -> &HirFunction {
        self.hir
            .functions
            .iter()
            .find(|function| function.name == name)
            .expect("HIR function must match AST")
    }

    fn function_name(&self, name: &str) -> String {
        self.function_names
            .get(name)
            .cloned()
            .unwrap_or_else(|| name.to_string())
    }

    fn binding_name(&self, name: &str) -> String {
        self.binding_names
            .get(name)
            .cloned()
            .unwrap_or_else(|| name.to_string())
    }
}

struct CanonicalRange<'a> {
    iterator: &'a str,
    start: &'a Expr,
    end: &'a Expr,
    line: usize,
}

fn canonical_range<'a>(
    initial: &'a Option<Box<Stmt>>,
    condition: &'a Option<Expr>,
    post: &'a Option<Expr>,
    line: usize,
) -> Result<CanonicalRange<'a>, TranslateError> {
    let (iterator, start) = match initial.as_deref() {
        Some(Stmt::Decl(name, Some(start), _, _)) => (name.as_str(), start),
        _ => return Err(noncanonical_range(line)),
    };
    let end = match condition {
        Some(Expr::Binary("<", left, end, _)) if matches!(&**left, Expr::Var(name, _) if name == iterator) => {
            &**end
        }
        _ => return Err(noncanonical_range(line)),
    };
    let valid_post = match post {
        Some(Expr::Assign(target, value, source, _))
            if matches!(&**target, LValue::Var(name, _) if name == iterator)
                && matches!(&**value, Expr::Num(1, _, _)) =>
        {
            matches!(
                source,
                AssignmentProvenance::Compound("+")
                    | AssignmentProvenance::PrefixIncrement
                    | AssignmentProvenance::PostfixIncrement
            )
        }
        _ => false,
    };
    if !valid_post {
        return Err(noncanonical_range(line));
    }
    Ok(CanonicalRange {
        iterator,
        start,
        end,
        line,
    })
}

fn noncanonical_range(line: usize) -> TranslateError {
    TranslateError::new(
        line,
        "noncanonical C for loop cannot be represented as a Rust range; use for (int i = start; i < end; i++) with unit positive stride",
    )
}

fn statements_always_return(statements: &[Stmt]) -> bool {
    statements.iter().any(statement_always_returns)
}

fn statement_always_returns(statement: &Stmt) -> bool {
    match statement {
        Stmt::Return(Some(_), _, _) => true,
        Stmt::If(_, body, _, source) if source.origin == IfOrigin::PlainBlock => {
            statements_always_return(body)
        }
        Stmt::If(_, body, otherwise, _) => {
            !otherwise.is_empty()
                && statements_always_return(body)
                && statements_always_return(otherwise)
        }
        _ => false,
    }
}

fn expression_has_side_effect(expression: &Expr) -> bool {
    match expression {
        Expr::Assign(..) | Expr::Call(..) => true,
        Expr::Index(_, index, _) | Expr::Unary(_, index, _) => expression_has_side_effect(index),
        Expr::Binary(_, left, right, _) => {
            expression_has_side_effect(left) || expression_has_side_effect(right)
        }
        Expr::Num(..) | Expr::Var(..) => false,
    }
}

fn collect_variables(expression: &Expr, output: &mut HashSet<String>) {
    match expression {
        Expr::Var(name, _) => {
            output.insert(name.clone());
        }
        Expr::Index(name, index, _) => {
            output.insert(name.clone());
            collect_variables(index, output);
        }
        Expr::Unary(_, value, _) => collect_variables(value, output),
        Expr::Binary(_, left, right, _) => {
            collect_variables(left, output);
            collect_variables(right, output);
        }
        Expr::Assign(target, value, _, _) => {
            match &**target {
                LValue::Var(name, _) => {
                    output.insert(name.clone());
                }
                LValue::Index(name, index, _) => {
                    output.insert(name.clone());
                    collect_variables(index, output);
                }
            }
            collect_variables(value, output);
        }
        Expr::Call(_, arguments, _) => {
            for argument in arguments {
                collect_variables(argument, output);
            }
        }
        Expr::Num(..) => {}
    }
}

fn statements_assign_to(statements: &[Stmt], name: &str) -> bool {
    statements.iter().any(|statement| match statement {
        Stmt::Decl(_, initial, _, _) => initial
            .as_ref()
            .is_some_and(|value| expression_assigns_to(value, name)),
        Stmt::DeclArray(_, _, initial, _, _, _) => initial
            .iter()
            .any(|value| expression_assigns_to(value, name)),
        Stmt::Expr(expression, _) | Stmt::Return(Some(expression), _, _) => {
            expression_assigns_to(expression, name)
        }
        Stmt::If(condition, body, otherwise, _) => {
            expression_assigns_to(condition, name)
                || statements_assign_to(body, name)
                || statements_assign_to(otherwise, name)
        }
        Stmt::While(condition, body, _) => {
            expression_assigns_to(condition, name) || statements_assign_to(body, name)
        }
        Stmt::For(initial, condition, post, body, _) => {
            initial.as_deref().is_some_and(|statement| {
                statements_assign_to(std::slice::from_ref(statement), name)
            }) || condition
                .as_ref()
                .is_some_and(|value| expression_assigns_to(value, name))
                || post
                    .as_ref()
                    .is_some_and(|value| expression_assigns_to(value, name))
                || statements_assign_to(body, name)
        }
        Stmt::Return(None, _, _) | Stmt::Break(_) | Stmt::Continue(_) => false,
    })
}

fn expression_assigns_to(expression: &Expr, name: &str) -> bool {
    match expression {
        Expr::Assign(target, value, _, _) => {
            matches!(&**target, LValue::Var(target, _) if target == name)
                || matches!(&**target, LValue::Index(target, _, _) if target == name)
                || expression_assigns_to(value, name)
        }
        Expr::Index(_, index, _) | Expr::Unary(_, index, _) => expression_assigns_to(index, name),
        Expr::Binary(_, left, right, _) => {
            expression_assigns_to(left, name) || expression_assigns_to(right, name)
        }
        Expr::Call(_, arguments, _) => arguments
            .iter()
            .any(|argument| expression_assigns_to(argument, name)),
        Expr::Num(..) | Expr::Var(..) => false,
    }
}

fn expression_line(expression: &Expr) -> usize {
    match expression {
        Expr::Var(_, line) | Expr::Index(_, _, line) | Expr::Call(_, _, line) => *line,
        Expr::Num(_, _, line)
        | Expr::Unary(_, _, line)
        | Expr::Binary(_, _, _, line)
        | Expr::Assign(_, _, _, line) => *line,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{assemble, c_to_asm, rust_to_asm, Pipeline};

    fn run_assembly(assembly: &str) -> i32 {
        let program = assemble(assembly).unwrap_or_else(|error| {
            panic!("generated assembly did not assemble: {error:?}\n{assembly}")
        });
        let mut pipeline = Pipeline::new(program);
        assert!(pipeline.run(1_000_000), "program did not halt:\n{assembly}");
        let snapshot = pipeline.snapshot();
        let halt = snapshot.halt.expect("program has no halt state");
        assert_eq!(halt.kind, "complete", "program trapped: {}", halt.message);
        snapshot.registers[10] as i32
    }

    fn run_c(source: &str) -> i32 {
        run_assembly(&c_to_asm(source).expect("C source did not compile"))
    }

    fn run_rust(source: &str) -> i32 {
        run_assembly(&rust_to_asm(source).expect("translated Rust did not compile"))
    }

    fn assert_round_trip(source: &str) -> String {
        let translated = translate(source).expect("C-to-Rust translation failed");
        super::super::parse_rust_unit(&translated).unwrap_or_else(|error| {
            panic!(
                "translated Rust did not reparse at line {}: {}\n{translated}",
                error.line, error.message
            )
        });
        assert_eq!(run_rust(&translated), run_c(source), "{translated}");
        translated
    }

    fn assert_rejected(source: &str, line: usize, reason: &str) {
        let error = translate(source).expect_err("translation unexpectedly succeeded");
        assert_eq!(error.line, line, "wrong source line: {error:?}");
        assert!(
            error.message.contains(reason),
            "missing reason '{reason}' in: {}",
            error.message
        );
    }

    #[test]
    fn c_to_rust_initialized_scalars_arithmetic_and_bitwise_execute_equivalently() {
        let translated = assert_round_trip(
            "int main() {
                int left = 21;
                int right = 6;
                int value = ((left + right) * 2 - 4) / 5;
                return (value << 2) ^ (~right & 7);
            }",
        );
        assert!(translated.contains("let left: i32 = 21;"));
        assert!(translated.contains("(!right)"));
    }

    #[test]
    fn c_to_rust_renames_rust_keyword_identifiers_and_executes_equivalently() {
        let translated = assert_round_trip(
            "int loop(int mut) {
                 int __riscvsim_mut = mut + 1;
                 int type = __riscvsim_mut + 1;
                 return type;
             }
             int main() {
                 int match = 5;
                 int fn[2] = {loop(match), 3};
                 fn[1] = fn[0] + 1;
                 return fn[1];
             }",
        );
        for invalid in [
            "fn loop(",
            "mut mut:",
            "let type:",
            "let match:",
            "let mut fn:",
        ] {
            assert!(!translated.contains(invalid), "{translated}");
        }
        assert!(translated.contains("__riscvsim_mut_1"), "{translated}");
    }

    #[test]
    fn c_to_rust_truthy_and_boolean_conditions_execute_equivalently() {
        assert_round_trip(
            "int main() {
                int value = 7;
                if (value && !(value < 3 || value == 9)) { return 11; }
                return 2;
            }",
        );
    }

    #[test]
    fn c_to_rust_statement_assignments_and_mutability_execute_equivalently() {
        let translated = assert_round_trip(
            "int adjust(int value) {
                value += 3;
                value *= 2;
                value--;
                ++value;
                return value;
            }
            int main() { return adjust(4); }",
        );
        assert!(translated.contains("fn adjust(mut value: i32)"));
        assert!(translated.contains("value += 3;"));
        assert!(translated.contains("value -= 1;"));
    }

    #[test]
    fn c_to_rust_partial_and_empty_array_initializers_execute_equivalently() {
        let translated = assert_round_trip(
            "int main() {
                int values[4] = {3, 5};
                int zeros[2] = {};
                values[3] = 7;
                return values[0] + values[1] + values[2] + values[3] + zeros[1];
            }",
        );
        assert!(translated.contains("[3, 5, 0, 0]"));
        assert!(translated.contains("[0, 0]"));
    }

    #[test]
    fn c_to_rust_canonical_range_and_iterator_index_execute_equivalently() {
        let translated = assert_round_trip(
            "int main() {
                int values[5] = {1, 2, 3, 4, 5};
                int total = 0;
                for (int i = 0; i < 5; i++) { total += values[i]; }
                return total;
            }",
        );
        assert!(translated.contains("for i in 0..5"));
        assert!(translated.contains("values[i]"));
    }

    #[test]
    fn c_to_rust_canonical_range_with_immutable_bound_executes_equivalently() {
        assert_round_trip(
            "int main() {
                int end = 6;
                int total = 0;
                for (int i = 2; i < end; i += 1) { total += i; }
                return total;
            }",
        );
    }

    #[test]
    fn c_to_rust_nested_canonical_ranges_execute_equivalently() {
        assert_round_trip(
            "int main() {
                int total = 0;
                for (int row = 0; row < 3; row++) {
                    for (int column = 0; column < 4; ++column) {
                        total += row + column;
                    }
                }
                return total;
            }",
        );
    }

    #[test]
    fn c_to_rust_while_break_and_continue_execute_equivalently() {
        assert_round_trip(
            "int main() {
                int value = 0;
                int total = 0;
                while (value < 9) {
                    value++;
                    if (value == 2) { continue; }
                    if (value == 6) { break; }
                    total += value;
                }
                return total;
            }",
        );
    }

    #[test]
    fn c_to_rust_forward_calls_and_recursion_execute_equivalently() {
        let translated = assert_round_trip(
            "int factorial(int value);
             int main() { return factorial(5); }
             int factorial(int value) {
                 if (value <= 1) { return 1; }
                 return value * factorial(value - 1);
             }",
        );
        assert!(translated.contains("fn factorial(value: i32) -> i32"));
    }

    #[test]
    fn c_to_rust_plain_blocks_and_empty_statements_execute_equivalently() {
        assert_round_trip(
            "int main() {
                int value = 2;
                ;
                { value += 5; }
                return value;
            }",
        );
    }

    #[test]
    fn c_to_rust_if_else_complete_returns_execute_equivalently() {
        assert_round_trip(
            "int choose(int value) {
                if (value < 0) { return -1; } else { return value + 1; }
            }
            int main() { return choose(4); }",
        );
    }

    #[test]
    fn c_to_rust_function_call_statement_executes_equivalently() {
        assert_round_trip(
            "int identity(int value) { return value; }
             int main() { identity(4); return identity(8); }",
        );
    }

    #[test]
    fn c_to_rust_negative_literal_index_is_rejected() {
        assert_rejected(
            "int main() { int values[2] = {1, 2}; return values[-1]; }",
            1,
            "array indexes",
        );
    }

    #[test]
    fn c_to_rust_uninitialized_scalar_is_rejected() {
        assert_rejected(
            "int main() {\nint value;\nreturn 0;\n}",
            2,
            "uninitialized local 'value'",
        );
    }

    #[test]
    fn c_to_rust_uninitialized_array_is_rejected() {
        assert_rejected(
            "int main() {\nint values[2];\nreturn 0;\n}",
            2,
            "uninitialized array 'values'",
        );
    }

    #[test]
    fn c_to_rust_returned_assignment_value_is_rejected() {
        assert_rejected(
            "int main() { int value = 0;\nreturn value = 4;\n}",
            2,
            "value-producing assignment",
        );
    }

    #[test]
    fn c_to_rust_chained_assignment_value_is_rejected() {
        assert_rejected(
            "int main() { int left = 0; int right = 0;\nleft = right = 5;\nreturn left; }",
            2,
            "value-producing assignment",
        );
    }

    #[test]
    fn c_to_rust_assignment_condition_is_rejected() {
        assert_rejected(
            "int main() { int value = 0;\nif (value = 3) { return value; }\nreturn 0; }",
            2,
            "value-producing assignment",
        );
    }

    #[test]
    fn c_to_rust_noncanonical_for_comparison_is_rejected() {
        assert_rejected(
            "int main() { int total = 0;\nfor (int i = 0; i <= 3; i++) { total += i; }\nreturn total; }",
            2,
            "noncanonical C for loop",
        );
    }

    #[test]
    fn c_to_rust_noncanonical_for_stride_is_rejected() {
        assert_rejected(
            "int main() { int total = 0;\nfor (int i = 0; i < 6; i += 2) { total += i; }\nreturn total; }",
            2,
            "noncanonical C for loop",
        );
    }

    #[test]
    fn c_to_rust_noncanonical_existing_iterator_is_rejected() {
        assert_rejected(
            "int main() { int i = 0; int total = 0;\nfor (i = 0; i < 3; i++) { total += i; }\nreturn total; }",
            2,
            "noncanonical C for loop",
        );
    }

    #[test]
    fn c_to_rust_mutable_range_bound_is_rejected() {
        assert_rejected(
            "int main() { int end = 4; int total = 0;\nfor (int i = 0; i < end; i++) { end -= 1; total += i; }\nreturn total; }",
            2,
            "mutable binding 'end'",
        );
    }

    #[test]
    fn c_to_rust_side_effecting_range_bound_is_rejected() {
        assert_rejected(
            "int bound() { return 4; }\nint main() { int total = 0;\nfor (int i = 0; i < bound(); i++) { total += i; }\nreturn total; }",
            3,
            "range bound must be side-effect free",
        );
    }

    #[test]
    fn c_to_rust_arbitrary_i32_array_index_is_rejected() {
        assert_rejected(
            "int main() { int values[2] = {4, 7}; int index = 1;\nreturn values[index];\n}",
            2,
            "arbitrary i32 array indexes",
        );
    }

    #[test]
    fn c_to_rust_comparison_result_consumed_as_integer_is_rejected() {
        assert_rejected(
            "int main() {\nreturn (3 < 4) + 5;\n}",
            2,
            "comparison or logical result used as an integer arithmetic operand",
        );
    }

    #[test]
    fn c_to_rust_logical_result_consumed_as_integer_is_rejected() {
        assert_rejected(
            "int main() { int value = 1;\nreturn value && 3;\n}",
            2,
            "comparison or logical result used as an integer return value",
        );
    }

    #[test]
    fn c_to_rust_range_iterator_modified_in_body_is_rejected() {
        assert_rejected(
            "int main() { int total = 0;\nfor (int i = 0; i < 4; i++) { i += 1; total += i; }\nreturn total; }",
            2,
            "iterator 'i' is modified",
        );
    }

    #[test]
    fn c_to_rust_range_iterator_used_after_loop_is_rejected() {
        assert_rejected(
            "int main() {\nfor (int i = 0; i < 2; i++) { }\nreturn i;\n}",
            3,
            "iterator 'i' is used outside its loop",
        );
    }

    #[test]
    fn c_to_rust_range_bound_referencing_iterator_is_rejected() {
        assert_rejected(
            "int main() {\nfor (int i = 0; i < i; i++) { }\nreturn 0;\n}",
            2,
            "range bound cannot reference its iterator",
        );
    }

    #[test]
    fn c_to_rust_bare_return_is_rejected() {
        assert_rejected("int main() {\nreturn;\n}", 2, "bare return");
    }

    #[test]
    fn c_to_rust_fallthrough_function_is_rejected() {
        assert_rejected(
            "int main() { int value = 3; value += 2; }",
            1,
            "can fall through",
        );
    }

    #[test]
    fn c_to_rust_synthetic_main_is_rejected() {
        assert_rejected(
            "int value = 3; return value;",
            1,
            "explicit function definitions",
        );
    }

    #[test]
    fn c_to_rust_break_outside_loop_is_rejected() {
        assert_rejected("int main() {\nbreak;\nreturn 0; }", 2, "break outside");
    }

    #[test]
    fn c_to_rust_continue_outside_loop_is_rejected() {
        assert_rejected(
            "int main() {\ncontinue;\nreturn 0; }",
            2,
            "continue outside",
        );
    }

    #[test]
    fn c_to_rust_array_used_as_scalar_is_rejected() {
        assert_rejected(
            "int main() { int values[2] = {1, 2};\nreturn values;\n}",
            2,
            "array and can only be used with an index",
        );
    }

    #[test]
    fn c_to_rust_scalar_used_as_array_is_rejected() {
        assert_rejected(
            "int main() { int value = 2;\nreturn value[0];\n}",
            2,
            "is not an array",
        );
    }

    #[test]
    fn c_to_rust_undefined_function_is_rejected() {
        assert_rejected(
            "int main() {\nreturn missing(3);\n}",
            2,
            "undefined function 'missing'",
        );
    }

    #[test]
    fn c_to_rust_wrong_function_arity_is_rejected() {
        assert_rejected(
            "int identity(int value) { return value; }\nint main() {\nreturn identity(1, 2);\n}",
            3,
            "expects 1 arguments, found 2",
        );
    }

    #[test]
    fn c_to_rust_duplicate_function_is_rejected() {
        assert_rejected(
            "int main() { return 1; }\nint main() { return 2; }",
            2,
            "defined twice",
        );
    }

    #[test]
    fn c_to_rust_duplicate_binding_is_rejected() {
        assert_rejected(
            "int main() { int value = 1;\nint value = 2;\nreturn value; }",
            2,
            "binding 'value' is declared twice",
        );
    }
}
