use super::hir::{typed_hir_from_cpp, HirBinding, HirFunction, HirType, TypedHir};
use super::identifiers::{identifier_map, IdentifierTarget};
use super::{
    ArrayInitProvenance, AssignmentProvenance, Expr, ExprStmtProvenance, Func, IfOrigin, LValue,
    LoopKind, ScalarType, Stmt, TranslateError,
};
use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

pub(super) fn translate(source: &str) -> Result<String, TranslateError> {
    let hir = typed_hir_from_cpp(source)?;
    Emitter::new(&hir)?.emit()
}

#[derive(Clone)]
struct Signature {
    parameters: Vec<HirType>,
    result: HirType,
}

struct Value {
    code: String,
    value_type: HirType,
}

#[derive(Clone)]
enum LoopContext {
    Natural,
    CFor(Expr),
}

struct Emitter<'a> {
    hir: &'a TypedHir,
    signatures: HashMap<String, Signature>,
    names: HashMap<String, String>,
    reserved: HashSet<String>,
    out: String,
    temp_counter: usize,
    loops: Vec<LoopContext>,
}

impl<'a> Emitter<'a> {
    fn new(hir: &'a TypedHir) -> Result<Self, TranslateError> {
        let mut signatures = HashMap::new();
        for function in &hir.ast.funcs {
            if signatures
                .insert(
                    function.name.clone(),
                    Signature {
                        parameters: function
                            .param_types
                            .iter()
                            .copied()
                            .map(Into::into)
                            .collect(),
                        result: function.return_type.into(),
                    },
                )
                .is_some()
            {
                return Err(TranslateError::new(
                    function.line,
                    format!("function '{}' is defined twice", function.name),
                ));
            }
        }
        let names = identifier_map(
            hir.ast
                .funcs
                .iter()
                .map(|function| function.name.as_str())
                .chain(hir.functions.iter().flat_map(|function| {
                    function
                        .bindings
                        .iter()
                        .map(|binding| binding.name.as_str())
                })),
            IdentifierTarget::Rust,
        );
        let reserved = names.values().cloned().collect();
        Ok(Self {
            hir,
            signatures,
            names,
            reserved,
            out: String::new(),
            temp_counter: 0,
            loops: Vec::new(),
        })
    }

    fn emit(mut self) -> Result<String, TranslateError> {
        self.out
            .push_str("// Generated by the StudyRISC-V C++-to-Rust translator.\n");
        self.out
            .push_str("// Compilable within the documented int/bool subset.\n\n");
        for (index, function) in self.hir.ast.funcs.iter().enumerate() {
            if index > 0 {
                self.out.push('\n');
            }
            self.emit_function(function)?;
        }
        Ok(self.out)
    }

    fn emit_function(&mut self, function: &Func) -> Result<(), TranslateError> {
        self.temp_counter = 0;
        self.loops.clear();
        let return_type = self.function_hir(&function.name).return_type;
        let mut seen = HashSet::new();
        for binding in &self.function_hir(&function.name).bindings {
            if !seen.insert(&binding.name) {
                return Err(TranslateError::new(
                    binding.line,
                    format!(
                        "binding '{}' is declared twice; the subset has one scope per function",
                        binding.name
                    ),
                ));
            }
        }
        let parameters = function
            .params
            .iter()
            .map(|name| {
                let binding = self.binding(function, name, function.line)?;
                Ok(format!(
                    "{}{}: {}",
                    if binding.mutable { "mut " } else { "" },
                    self.target_name(name),
                    type_name(binding.value_type)
                ))
            })
            .collect::<Result<Vec<_>, TranslateError>>()?
            .join(", ");
        let return_suffix = if return_type == HirType::Unit {
            String::new()
        } else {
            format!(" -> {}", type_name(return_type))
        };
        let _ = writeln!(
            self.out,
            "fn {}({parameters}){return_suffix} {{",
            self.target_name(&function.name)
        );
        self.emit_statements(function, &function.body, 1)?;
        if return_type != HirType::Unit && !statements_always_return(&function.body) {
            self.line(
                1,
                &format!("return {};", default_value(return_type, function.line)?),
            );
        }
        self.out.push_str("}\n");
        Ok(())
    }

    fn emit_statements(
        &mut self,
        function: &Func,
        statements: &[Stmt],
        depth: usize,
    ) -> Result<(), TranslateError> {
        for statement in statements {
            self.emit_statement(function, statement, depth)?;
        }
        Ok(())
    }

    fn emit_statement(
        &mut self,
        function: &Func,
        statement: &Stmt,
        depth: usize,
    ) -> Result<(), TranslateError> {
        match statement {
            Stmt::Decl(name, initial, _, line) => {
                let binding = self.binding(function, name, *line)?;
                let value_type = binding.value_type;
                let mutable = binding.mutable;
                let value = if let Some(initial) = initial {
                    let value = self.lower_expression(function, initial, depth)?;
                    self.coerce(value, value_type, depth, *line)?.code
                } else {
                    default_value(value_type, *line)?.to_string()
                };
                self.line(
                    depth,
                    &format!(
                        "let {}{}: {} = {value};",
                        if mutable { "mut " } else { "" },
                        self.target_name(name),
                        type_name(value_type)
                    ),
                );
            }
            Stmt::DeclArray(name, size, initial, source, initializer, line) => {
                let binding = self.binding(function, name, *line)?;
                let mutable = binding.mutable;
                let mut values = Vec::new();
                for expression in initial {
                    let value = self.lower_expression(function, expression, depth)?;
                    values.push(self.coerce(value, HirType::I32, depth, *line)?.code);
                }
                let initializer = if !source.initialized
                    || *initializer == ArrayInitProvenance::Absent
                    || values.is_empty()
                {
                    format!("[0; {size}]")
                } else {
                    values.resize(*size, "0".to_string());
                    format!("[{}]", values.join(", "))
                };
                self.line(
                    depth,
                    &format!(
                        "let {}{}: [i32; {size}] = {initializer};",
                        if mutable { "mut " } else { "" },
                        self.target_name(name)
                    ),
                );
            }
            Stmt::Expr(_, ExprStmtProvenance::Empty) => {}
            Stmt::Expr(expression, ExprStmtProvenance::Expression) => {
                let value = self.lower_expression(function, expression, depth)?;
                self.line(depth, &format!("{};", value.code));
            }
            Stmt::If(_, body, _, source) if source.origin == IfOrigin::PlainBlock => {
                self.line(depth, "{");
                self.emit_statements(function, body, depth + 1)?;
                self.line(depth, "}");
            }
            Stmt::If(condition, body, otherwise, _) => {
                let condition = self.condition(function, condition, depth)?;
                self.line(depth, &format!("if {} {{", condition.code));
                self.emit_statements(function, body, depth + 1)?;
                if otherwise.is_empty() {
                    self.line(depth, "}");
                } else {
                    self.line(depth, "} else {");
                    self.emit_statements(function, otherwise, depth + 1)?;
                    self.line(depth, "}");
                }
            }
            Stmt::While(condition, body, source) => {
                if source.kind != LoopKind::While {
                    return Err(TranslateError::new(
                        source.line,
                        "internal: C++ AST contains a non-while loop in a while statement",
                    ));
                }
                self.line(depth, "loop {");
                let condition = self.condition(function, condition, depth + 1)?;
                self.line(depth + 1, &format!("if (!{}) {{", condition.code));
                self.line(depth + 2, "break;");
                self.line(depth + 1, "}");
                self.loops.push(LoopContext::Natural);
                let result = self.emit_statements(function, body, depth + 1);
                self.loops.pop();
                result?;
                self.line(depth, "}");
            }
            Stmt::For(initial, condition, post, body, source) => {
                if source.kind != LoopKind::CFor {
                    return Err(TranslateError::new(
                        source.line,
                        "internal: C++ AST contains a non-C++ for loop",
                    ));
                }
                self.line(depth, "{");
                if let Some(initial) = initial {
                    self.emit_statement(function, initial, depth + 1)?;
                }
                self.line(depth + 1, "loop {");
                if let Some(condition) = condition {
                    let condition = self.condition(function, condition, depth + 2)?;
                    self.line(depth + 2, &format!("if (!{}) {{", condition.code));
                    self.line(depth + 3, "break;");
                    self.line(depth + 2, "}");
                }
                self.loops.push(match post {
                    Some(post) => LoopContext::CFor(post.clone()),
                    None => LoopContext::Natural,
                });
                let result = self.emit_statements(function, body, depth + 2);
                self.loops.pop();
                result?;
                if let Some(post) = post {
                    let value = self.lower_expression(function, post, depth + 2)?;
                    self.line(depth + 2, &format!("{};", value.code));
                }
                self.line(depth + 1, "}");
                self.line(depth, "}");
            }
            Stmt::Return(value, _, line) => {
                let expected = self.function_hir(&function.name).return_type;
                let value = match (expected, value) {
                    (HirType::Unit, None) => {
                        self.line(depth, "return;");
                        return Ok(());
                    }
                    (HirType::Unit, Some(_)) => {
                        return Err(TranslateError::new(
                            *line,
                            "void functions cannot return a value",
                        ));
                    }
                    (_, Some(value)) => {
                        let value = self.lower_expression(function, value, depth)?;
                        self.coerce(value, expected, depth, *line)?.code
                    }
                    (_, None) => default_value(expected, *line)?.to_string(),
                };
                self.line(depth, &format!("return {value};"));
            }
            Stmt::Break(line) => {
                if self.loops.is_empty() {
                    return Err(TranslateError::new(*line, "break outside a loop"));
                }
                self.line(depth, "break;");
            }
            Stmt::Continue(line) => {
                let context = self
                    .loops
                    .last()
                    .cloned()
                    .ok_or_else(|| TranslateError::new(*line, "continue outside a loop"))?;
                if let LoopContext::CFor(post) = context {
                    let value = self.lower_expression(function, &post, depth)?;
                    self.line(depth, &format!("{};", value.code));
                }
                self.line(depth, "continue;");
            }
        }
        Ok(())
    }

    fn lower_expression(
        &mut self,
        function: &Func,
        expression: &Expr,
        depth: usize,
    ) -> Result<Value, TranslateError> {
        match expression {
            Expr::Num(value, value_type, _) => Ok(Value {
                code: match value_type {
                    ScalarType::Bool => (*value != 0).to_string(),
                    _ => value.to_string(),
                },
                value_type: (*value_type).into(),
            }),
            Expr::Var(name, line) => {
                let binding = self.scalar_binding(function, name, *line)?;
                Ok(Value {
                    code: self.target_name(name),
                    value_type: binding.value_type,
                })
            }
            Expr::Index(name, index, line) => {
                self.array_binding(function, name, *line)?;
                let index = self.lower_expression(function, index, depth)?;
                let index = self.coerce(index, HirType::I32, depth, *line)?;
                Ok(Value {
                    code: format!("{}[({} as usize)]", self.target_name(name), index.code),
                    value_type: HirType::I32,
                })
            }
            Expr::Unary("!", value, _) => {
                let value = self.condition(function, value, depth)?;
                Ok(Value {
                    code: format!("(!{})", value.code),
                    value_type: HirType::Bool,
                })
            }
            Expr::Unary(operator @ ("~" | "-"), value, line) => {
                let value = self.lower_expression(function, value, depth)?;
                let value = self.coerce(value, HirType::I32, depth, *line)?;
                let rust_operator = if *operator == "~" { "!" } else { "-" };
                Ok(Value {
                    code: format!("({rust_operator}{})", value.code),
                    value_type: HirType::I32,
                })
            }
            Expr::Unary(_, _, line) => Err(TranslateError::new(
                *line,
                "unsupported unary expression in C++-to-Rust translation",
            )),
            Expr::Binary("&&", left, right, line) => {
                self.lower_short_circuit(function, left, right, true, depth, *line)
            }
            Expr::Binary("||", left, right, line) => {
                self.lower_short_circuit(function, left, right, false, depth, *line)
            }
            Expr::Binary(operator @ ("==" | "!="), left, right, line) => {
                let left = self.lower_expression(function, left, depth)?;
                let left_type = left.value_type;
                let right = self.lower_expression(function, right, depth)?;
                let right_type = right.value_type;
                let (left, right) = if left_type == HirType::Bool && right_type == HirType::Bool {
                    (left, right)
                } else {
                    (
                        self.coerce(left, HirType::I32, depth, *line)?,
                        self.coerce(right, HirType::I32, depth, *line)?,
                    )
                };
                Ok(Value {
                    code: format!("({} {operator} {})", left.code, right.code),
                    value_type: HirType::Bool,
                })
            }
            Expr::Binary(operator @ ("<" | "<=" | ">" | ">="), left, right, line) => {
                let left = self.lower_expression(function, left, depth)?;
                let left = self.coerce(left, HirType::I32, depth, *line)?;
                let right = self.lower_expression(function, right, depth)?;
                let right = self.coerce(right, HirType::I32, depth, *line)?;
                Ok(Value {
                    code: format!("({} {operator} {})", left.code, right.code),
                    value_type: HirType::Bool,
                })
            }
            Expr::Binary(operator, left, right, line) => {
                let left = self.lower_expression(function, left, depth)?;
                let left = self.coerce(left, HirType::I32, depth, *line)?;
                let right = self.lower_expression(function, right, depth)?;
                let right = self.coerce(right, HirType::I32, depth, *line)?;
                Ok(Value {
                    code: format!("({} {operator} {})", left.code, right.code),
                    value_type: HirType::I32,
                })
            }
            Expr::Assign(target, value, source, line) => {
                self.lower_assignment(function, target, value, *source, depth, *line)
            }
            Expr::Call(name, arguments, line) => {
                let signature = self.signatures.get(name).cloned().ok_or_else(|| {
                    TranslateError::new(*line, format!("call to undefined function '{name}'"))
                })?;
                if arguments.len() != signature.parameters.len() {
                    return Err(TranslateError::new(
                        *line,
                        format!(
                            "function '{name}' expects {} arguments, found {}",
                            signature.parameters.len(),
                            arguments.len()
                        ),
                    ));
                }
                let mut emitted = Vec::new();
                for (argument, expected) in arguments.iter().zip(signature.parameters) {
                    let value = self.lower_expression(function, argument, depth)?;
                    emitted.push(self.coerce(value, expected, depth, *line)?.code);
                }
                Ok(Value {
                    code: format!("{}({})", self.target_name(name), emitted.join(", ")),
                    value_type: signature.result,
                })
            }
        }
    }

    fn lower_short_circuit(
        &mut self,
        function: &Func,
        left: &Expr,
        right: &Expr,
        and_operator: bool,
        depth: usize,
        line: usize,
    ) -> Result<Value, TranslateError> {
        let left = self.condition(function, left, depth)?;
        let result = self.fresh_temp();
        self.line(depth, &format!("let mut {result}: bool = {};", left.code));
        self.line(
            depth,
            &format!("if {}{result} {{", if and_operator { "" } else { "!" }),
        );
        let right = self.condition(function, right, depth + 1)?;
        self.line(depth + 1, &format!("{result} = {};", right.code));
        self.line(depth, "}");
        let _ = line;
        Ok(Value {
            code: result,
            value_type: HirType::Bool,
        })
    }

    fn lower_assignment(
        &mut self,
        function: &Func,
        target: &LValue,
        value: &Expr,
        source: AssignmentProvenance,
        depth: usize,
        line: usize,
    ) -> Result<Value, TranslateError> {
        let target_type = self.lvalue_type(function, target)?;
        if source == AssignmentProvenance::Simple {
            let value = self.lower_expression(function, value, depth)?;
            let value = self.coerce(value, target_type, depth, line)?;
            let result = self.fresh_temp();
            self.line(
                depth,
                &format!("let {result}: {} = {};", type_name(target_type), value.code),
            );
            let target = self.lower_lvalue(function, target, depth)?;
            self.line(depth, &format!("{} = {result};", target.code));
            return Ok(Value {
                code: result,
                value_type: target_type,
            });
        }

        let target = self.lower_lvalue(function, target, depth)?;
        let original = self.fresh_temp();
        self.line(
            depth,
            &format!(
                "let {original}: {} = {};",
                type_name(target_type),
                target.code
            ),
        );
        let original_numeric = self.coerce(
            Value {
                code: original.clone(),
                value_type: target_type,
            },
            HirType::I32,
            depth,
            line,
        )?;
        let value = self.lower_expression(function, value, depth)?;
        let value = self.coerce(value, HirType::I32, depth, line)?;
        let (operator, postfix) = match source {
            AssignmentProvenance::Compound(operator) => (operator, false),
            AssignmentProvenance::PrefixIncrement => ("+", false),
            AssignmentProvenance::PrefixDecrement => ("-", false),
            AssignmentProvenance::PostfixIncrement => ("+", true),
            AssignmentProvenance::PostfixDecrement => ("-", true),
            AssignmentProvenance::Simple => unreachable!(),
        };
        let computed = Value {
            code: format!("({} {operator} {})", original_numeric.code, value.code),
            value_type: HirType::I32,
        };
        let computed = self.coerce(computed, target_type, depth, line)?;
        let updated = self.fresh_temp();
        self.line(
            depth,
            &format!(
                "let {updated}: {} = {};",
                type_name(target_type),
                computed.code
            ),
        );
        self.line(depth, &format!("{} = {updated};", target.code));
        Ok(Value {
            code: if postfix { original } else { updated },
            value_type: target_type,
        })
    }

    fn lower_lvalue(
        &mut self,
        function: &Func,
        target: &LValue,
        depth: usize,
    ) -> Result<Value, TranslateError> {
        match target {
            LValue::Var(name, line) => {
                let binding = self.scalar_binding(function, name, *line)?;
                Ok(Value {
                    code: self.target_name(name),
                    value_type: binding.value_type,
                })
            }
            LValue::Index(name, index, line) => {
                self.array_binding(function, name, *line)?;
                let index = self.lower_expression(function, index, depth)?;
                let index = self.coerce(index, HirType::I32, depth, *line)?;
                let snapshot = self.fresh_temp();
                self.line(depth, &format!("let {snapshot}: i32 = {};", index.code));
                Ok(Value {
                    code: format!("{}[({snapshot} as usize)]", self.target_name(name)),
                    value_type: HirType::I32,
                })
            }
        }
    }

    fn lvalue_type(&self, function: &Func, target: &LValue) -> Result<HirType, TranslateError> {
        match target {
            LValue::Var(name, line) => Ok(self.scalar_binding(function, name, *line)?.value_type),
            LValue::Index(name, _, line) => {
                self.array_binding(function, name, *line)?;
                Ok(HirType::I32)
            }
        }
    }

    fn condition(
        &mut self,
        function: &Func,
        expression: &Expr,
        depth: usize,
    ) -> Result<Value, TranslateError> {
        let value = self.lower_expression(function, expression, depth)?;
        self.coerce(value, HirType::Bool, depth, expression_line(expression))
    }

    fn coerce(
        &mut self,
        value: Value,
        expected: HirType,
        depth: usize,
        line: usize,
    ) -> Result<Value, TranslateError> {
        if value.value_type == expected {
            return Ok(value);
        }
        match (value.value_type, expected) {
            (HirType::I32, HirType::Bool) => Ok(Value {
                code: format!("({} != 0)", value.code),
                value_type: HirType::Bool,
            }),
            (HirType::Bool, HirType::I32) => {
                let result = self.fresh_temp();
                self.line(depth, &format!("let mut {result}: i32 = 0;"));
                self.line(depth, &format!("if {} {{", value.code));
                self.line(depth + 1, &format!("{result} = 1;"));
                self.line(depth, "}");
                Ok(Value {
                    code: result,
                    value_type: HirType::I32,
                })
            }
            _ => Err(TranslateError::new(
                line,
                format!(
                    "cannot convert {} to {} in C++-to-Rust translation",
                    type_name(value.value_type),
                    type_name(expected)
                ),
            )),
        }
    }

    fn scalar_binding(
        &self,
        function: &Func,
        name: &str,
        line: usize,
    ) -> Result<&HirBinding, TranslateError> {
        let binding = self.binding(function, name, line)?;
        if binding.array_len.is_some() {
            return Err(TranslateError::new(
                line,
                format!("'{name}' is an array and can only be used with an index"),
            ));
        }
        Ok(binding)
    }

    fn array_binding(
        &self,
        function: &Func,
        name: &str,
        line: usize,
    ) -> Result<&HirBinding, TranslateError> {
        let binding = self.binding(function, name, line)?;
        if binding.array_len.is_none() {
            return Err(TranslateError::new(
                line,
                format!("'{name}' is not an array"),
            ));
        }
        Ok(binding)
    }

    fn binding(
        &self,
        function: &Func,
        name: &str,
        line: usize,
    ) -> Result<&HirBinding, TranslateError> {
        self.function_hir(&function.name)
            .bindings
            .iter()
            .find(|binding| binding.name == name)
            .ok_or_else(|| TranslateError::new(line, format!("binding '{name}' is not declared")))
    }

    fn function_hir(&self, name: &str) -> &HirFunction {
        self.hir
            .functions
            .iter()
            .find(|function| function.name == name)
            .expect("HIR function must match AST")
    }

    fn fresh_temp(&mut self) -> String {
        loop {
            self.temp_counter += 1;
            let candidate = format!("__riscvsim_tmp_{}", self.temp_counter);
            if self.reserved.insert(candidate.clone()) {
                return candidate;
            }
        }
    }

    fn target_name(&self, source: &str) -> String {
        self.names
            .get(source)
            .cloned()
            .unwrap_or_else(|| source.to_string())
    }

    fn line(&mut self, depth: usize, text: &str) {
        let _ = writeln!(self.out, "{}{text}", "    ".repeat(depth));
    }
}

fn type_name(value_type: HirType) -> &'static str {
    match value_type {
        HirType::I32 => "i32",
        HirType::Bool => "bool",
        HirType::Unit => "()",
    }
}

fn default_value(value_type: HirType, line: usize) -> Result<&'static str, TranslateError> {
    match value_type {
        HirType::I32 => Ok("0"),
        HirType::Bool => Ok("false"),
        HirType::Unit => Err(TranslateError::new(
            line,
            "unit values have no scalar default",
        )),
    }
}

fn statements_always_return(statements: &[Stmt]) -> bool {
    statements.iter().any(statement_always_returns)
}

fn statement_always_returns(statement: &Stmt) -> bool {
    match statement {
        Stmt::Return(_, _, _) => true,
        Stmt::If(_, body, _, source) if source.origin == IfOrigin::PlainBlock => {
            statements_always_return(body)
        }
        Stmt::If(_, body, otherwise, _) => {
            !otherwise.is_empty()
                && statements_always_return(body)
                && statements_always_return(otherwise)
        }
        _ => false,
    }
}

fn expression_line(expression: &Expr) -> usize {
    match expression {
        Expr::Var(_, line) | Expr::Index(_, _, line) | Expr::Call(_, _, line) => *line,
        Expr::Assign(_, _, _, line)
        | Expr::Unary(_, _, line)
        | Expr::Binary(_, _, _, line)
        | Expr::Num(_, _, line) => *line,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::assembler::assemble;
    use crate::assembler64::assemble64;
    use crate::pipeline::Pipeline;
    use crate::pipeline64::Pipeline64;

    fn run_rv32(assembly: &str) -> i32 {
        let program = assemble(assembly).unwrap_or_else(|errors| {
            panic!("generated RV32 did not assemble: {errors:?}\n{assembly}")
        });
        let mut pipeline = Pipeline::new(program);
        assert!(pipeline.run(1_000_000), "RV32 did not halt:\n{assembly}");
        let halt = pipeline.snapshot().halt.expect("missing RV32 halt state");
        assert_eq!(halt.kind, "complete", "RV32 trapped: {}", halt.message);
        pipeline.registers()[10] as i32
    }

    fn run_rv64(assembly: &str) -> i32 {
        let program = assemble64(assembly).unwrap_or_else(|errors| {
            panic!("generated RV64 did not assemble: {errors:?}\n{assembly}")
        });
        let mut pipeline = Pipeline64::new(program);
        assert!(pipeline.run(1_000_000), "RV64 did not halt:\n{assembly}");
        let halt = pipeline.snapshot().halt.expect("missing RV64 halt state");
        assert_eq!(halt.kind, "complete", "RV64 trapped: {}", halt.message);
        pipeline.registers()[10] as u32 as i32
    }

    fn assert_equivalent(source: &str, expected: i32) -> String {
        let rust = translate(source).unwrap_or_else(|error| {
            panic!(
                "C++-to-Rust failed at line {}: {}",
                error.line, error.message
            )
        });
        let cpp32 = super::super::cpp_to_asm(source).expect("C++ RV32 compilation failed");
        let rust32 = super::super::rust_to_asm(&rust)
            .unwrap_or_else(|error| panic!("generated Rust RV32 failed: {error:?}\n{rust}"));
        let cpp64 = super::super::cpp_to_asm64(source).expect("C++ RV64 compilation failed");
        let rust64 = super::super::rust_to_asm64(&rust)
            .unwrap_or_else(|error| panic!("generated Rust RV64 failed: {error:?}\n{rust}"));
        assert_eq!(run_rv32(&cpp32), expected, "unexpected C++ RV32 result");
        assert_eq!(
            run_rv32(&rust32),
            expected,
            "unexpected Rust RV32 result\n{rust}"
        );
        assert_eq!(run_rv64(&cpp64), expected, "unexpected C++ RV64 result");
        assert_eq!(
            run_rv64(&rust64),
            expected,
            "unexpected Rust RV64 result\n{rust}"
        );
        rust
    }

    #[test]
    fn cpp_to_rust_integer_arithmetic_executes_equivalently() {
        assert_equivalent(
            "int main() { int value = 7; return (value * 4 - 3) / 5 + 2; }",
            7,
        );
    }

    #[test]
    fn cpp_to_rust_auto_bool_assignment_executes_equivalently() {
        let rust = assert_equivalent("int main() { auto flag = true; flag = 7; return flag; }", 1);
        assert!(rust.contains("flag: bool"), "{rust}");
        assert!(rust.contains("(7 != 0)"), "{rust}");
    }

    #[test]
    fn cpp_to_rust_comparison_inferred_bool_executes_equivalently() {
        assert_equivalent(
            "int main() { int value = 3; auto ready = value < 4; ready = 0; return ready; }",
            0,
        );
    }

    #[test]
    fn cpp_to_rust_explicit_bool_conversions_execute_equivalently() {
        assert_equivalent(
            "bool ready(int value) { bool flag = value; return flag; } int main() { return ready(9) + ready(0); }",
            1,
        );
    }

    #[test]
    fn cpp_to_rust_bool_arguments_and_returns_execute_equivalently() {
        assert_equivalent(
            "int choose(bool enabled) { if (enabled) return 8; return 3; } bool nonzero(int value) { return value; } int main() { return choose(nonzero(7)); }",
            8,
        );
    }

    #[test]
    fn cpp_to_rust_bool_integral_promotion_executes_equivalently() {
        assert_equivalent(
            "int main() { bool left = true; auto right = false; return left * 4 + right + (left | right); }",
            5,
        );
    }

    #[test]
    fn cpp_to_rust_logical_short_circuit_preserves_side_effects() {
        assert_equivalent(
            "int main() { int value = 0; bool first = false && (value = 4); bool second = true || (value = 8); return value + first + second; }",
            1,
        );
    }

    #[test]
    fn cpp_to_rust_alternative_logical_tokens_execute_equivalently() {
        assert_equivalent(
            "int main() { auto ready = true and not false; if (ready or false) return 7; return 0; }",
            7,
        );
    }

    #[test]
    fn cpp_to_rust_chained_assignment_value_executes_equivalently() {
        assert_equivalent(
            "int main() { int first = 0; int second = 0; return first = second = 7; }",
            7,
        );
    }

    #[test]
    fn cpp_to_rust_prefix_and_postfix_values_execute_equivalently() {
        assert_equivalent(
            "int main() { int value = 3; int old = value++; int fresh = ++value; return old * 10 + fresh; }",
            35,
        );
    }

    #[test]
    fn cpp_to_rust_compound_assignment_result_executes_equivalently() {
        assert_equivalent(
            "int main() { int value = 5; return (value *= 3) + value; }",
            30,
        );
    }

    #[test]
    fn cpp_to_rust_bool_compound_assignment_normalizes() {
        assert_equivalent(
            "int main() { bool flag = true; flag += 8; return flag; }",
            1,
        );
    }

    #[test]
    fn cpp_to_rust_indexed_compound_evaluates_index_once() {
        assert_equivalent(
            "int main() { int values[3] = {2, 3, 4}; int index = 0; values[index++] += 5; return index * 10 + values[0]; }",
            17,
        );
    }

    #[test]
    fn cpp_to_rust_indexed_postfix_preserves_old_value() {
        assert_equivalent(
            "int main() { int values[2] = {4, 8}; int index = 0; int old = values[index++]++; return old * 10 + values[0] + index; }",
            46,
        );
    }

    #[test]
    fn cpp_to_rust_simple_indexed_assignment_preserves_rhs_first_order() {
        assert_equivalent(
            "int main() { int values[3] = {4, 5, 6}; int index = 0; values[index++] = (index = 1); return index * 10 + values[1]; }",
            21,
        );
    }

    #[test]
    fn cpp_to_rust_arbitrary_array_index_executes_equivalently() {
        assert_equivalent(
            "int main() { int values[4] = {2, 4, 6, 8}; int index = 1; index += 2; return values[index]; }",
            8,
        );
    }

    #[test]
    fn cpp_to_rust_uninitialized_scalar_assigned_before_read_executes() {
        assert_equivalent("int main() { int value; value = 9; return value; }", 9);
    }

    #[test]
    fn cpp_to_rust_uninitialized_array_assigned_before_read_executes() {
        assert_equivalent(
            "int main() { int values[2]; values[1] = 7; return values[1]; }",
            7,
        );
    }

    #[test]
    fn cpp_to_rust_partial_and_empty_array_initializers_execute() {
        assert_equivalent(
            "int main() { int first[3] = {4}; int second[2] = {}; return first[0] + first[2] + second[1]; }",
            4,
        );
    }

    #[test]
    fn cpp_to_rust_general_for_loop_executes_equivalently() {
        assert_equivalent(
            "int main() { int total = 0; for (int i = 5; i > 0; i -= 2) total += i; return total; }",
            9,
        );
    }

    #[test]
    fn cpp_to_rust_for_expression_initializer_and_post_execute() {
        assert_equivalent(
            "int main() { int i = 0; int total = 0; for (i = 1; i < 9; i *= 2) total += i; return total; }",
            15,
        );
    }

    #[test]
    fn cpp_to_rust_for_without_condition_uses_break() {
        assert_equivalent(
            "int main() { int value = 0; for (;;) { value++; if (value == 4) break; } return value; }",
            4,
        );
    }

    #[test]
    fn cpp_to_rust_for_continue_executes_post_once() {
        assert_equivalent(
            "int main() { int total = 0; for (int i = 0; i < 6; i++) { if (i < 3) continue; total += i; } return total; }",
            12,
        );
    }

    #[test]
    fn cpp_to_rust_nested_loop_continue_uses_nearest_loop() {
        assert_equivalent(
            "int main() { int total = 0; for (int i = 0; i < 3; i++) { int j = 0; while (j < 3) { j++; if (j < 3) continue; total += i; } } return total; }",
            3,
        );
    }

    #[test]
    fn cpp_to_rust_assignment_in_loop_condition_executes_equivalently() {
        assert_equivalent(
            "int next(int value) { return value - 1; } int main() { int value = 4; int total = 0; while (value = next(value)) total += value; return total; }",
            6,
        );
    }

    #[test]
    fn cpp_to_rust_calls_forward_definitions_and_recursion_execute() {
        assert_equivalent(
            "int main() { return factorial(5); } int factorial(int value) { if (value < 2) return 1; return value * factorial(value - 1); }",
            120,
        );
    }

    #[test]
    fn cpp_to_rust_prototypes_do_not_duplicate_definitions() {
        assert_equivalent(
            "int twice(int value); int main() { return twice(6); } int twice(int value) { return value + value; }",
            12,
        );
    }

    #[test]
    fn cpp_to_rust_assignment_arguments_preserve_order() {
        assert_equivalent(
            "int combine(int left, int right) { return left * 10 + right; } int main() { int value = 0; return combine(value = 3, value += 2) + value; }",
            40,
        );
    }

    #[test]
    fn cpp_to_rust_assignment_return_value_executes_equivalently() {
        assert_equivalent(
            "bool set(bool flag) { return flag = 7; } int main() { return set(false); }",
            1,
        );
    }

    #[test]
    fn cpp_to_rust_integer_operator_surface_executes_equivalently() {
        assert_equivalent(
            "int main() { int value = 29; int mixed = ((value % 6) << 3) | ((value / 4) ^ 2); return mixed + (~0 & 3); }",
            48,
        );
    }

    #[test]
    fn cpp_to_rust_explicit_int_from_bool_remains_integer_storage() {
        assert_equivalent("int main() { int flag = 1 < 2; flag = 7; return flag; }", 7);
    }

    #[test]
    fn cpp_to_rust_auto_integer_remains_integer_storage() {
        assert_equivalent("int main() { auto value = 3; value = 9; return value; }", 9);
    }

    #[test]
    fn cpp_to_rust_integer_and_assignment_conditions_execute() {
        assert_equivalent(
            "int main() { int value = 0; if (value = 4) value += 2; if (0) value = 99; return value; }",
            6,
        );
    }

    #[test]
    fn cpp_to_rust_bool_prototype_signature_executes_equivalently() {
        assert_equivalent(
            "bool ready(bool value); int main() { return ready(9); } bool ready(bool value) { return value; }",
            1,
        );
    }

    #[test]
    fn cpp_to_rust_bare_bool_return_uses_false() {
        assert_equivalent("bool ready() { return; } int main() { return ready(); }", 0);
    }

    #[test]
    fn cpp_to_rust_void_helpers_execute_equivalently() {
        let rust = assert_equivalent(
            "void touch(int value) { int copy = value; return; } int main() { touch(3); return 7; }",
            7,
        );
        assert!(rust.contains("fn touch(value: i32) {"), "{rust}");
        assert!(rust.contains("return;"), "{rust}");
    }

    #[test]
    fn cpp_to_rust_fallthrough_matches_simulator_default_return() {
        assert_equivalent(
            "int helper() { int value = 3; } int main() { return helper(); }",
            0,
        );
    }

    #[test]
    fn cpp_to_rust_keyword_identifiers_are_renamed_consistently() {
        let rust = assert_equivalent(
            "int match(int mut) { int loop = mut + 1; return loop; } int main() { return match(6); }",
            7,
        );
        assert!(!rust.contains("fn match("), "{rust}");
        assert!(!rust.contains("int mut"), "{rust}");
    }

    #[test]
    fn cpp_to_rust_synthetic_main_executes_equivalently() {
        assert_equivalent("int value = 4; value += 3; return value;", 7);
    }

    #[test]
    fn cpp_to_rust_plain_blocks_and_if_else_execute_equivalently() {
        assert_equivalent(
            "int main() { int value = 2; { value += 3; } if (value > 4) value *= 2; else value = 0; return value; }",
            10,
        );
    }

    #[test]
    fn cpp_to_rust_frontend_rejections_remain_source_anchored() {
        for (source, reason) in [
            ("class Value {}; int main() { return 0; }", "classes"),
            (
                "int main() { bool flag = true; ++flag; return flag; }",
                "not valid on bool",
            ),
            (
                "int main(int value) { return value; }",
                "main() cannot take parameters",
            ),
        ] {
            let error = translate(source).expect_err("invalid C++ should be rejected");
            assert_eq!(error.line, 1, "{error:?}");
            assert!(error.message.contains(reason), "{error:?}");
        }
    }
}
