use super::hir::{
    typed_hir_from_rust, HirBinding, HirFunction, HirType, HirTypeAnnotation, TypedHir,
};
use super::identifiers::{identifier_map, IdentifierTarget};
use super::{
    ArrayInitProvenance, AssignmentProvenance, Expr, Func, IfOrigin, LValue, LoopKind, Stmt,
    TranslateError,
};
use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

pub(super) fn translate(source: &str) -> Result<String, TranslateError> {
    let hir = typed_hir_from_rust(source)?;
    Emitter::new(&hir, TargetDialect::C)?.emit()
}

pub(super) fn translate_cpp(source: &str) -> Result<String, TranslateError> {
    let hir = typed_hir_from_rust(source)?;
    Emitter::new(&hir, TargetDialect::Cpp)?.emit()
}

pub(super) fn validate(hir: &TypedHir) -> Result<(), TranslateError> {
    // The emitter's type walk is the authoritative Rust subset validator.
    // Discarding its text keeps RV32/RV64 compilation on exactly the same
    // accepted-language boundary without duplicating semantic rules.
    Emitter::new(hir, TargetDialect::C)?.emit().map(|_| ())
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum TargetDialect {
    C,
    Cpp,
}

#[derive(Clone)]
struct Signature {
    parameters: Vec<HirType>,
    result: HirType,
}

struct Emitter<'a> {
    hir: &'a TypedHir,
    signatures: HashMap<String, Signature>,
    names: HashMap<String, String>,
    out: String,
    reserved: HashSet<String>,
    range_counter: usize,
    loop_depth: usize,
    target: TargetDialect,
}

impl<'a> Emitter<'a> {
    fn new(hir: &'a TypedHir, target: TargetDialect) -> Result<Self, TranslateError> {
        let mut signatures = HashMap::new();
        for function in &hir.ast.funcs {
            if signatures
                .insert(
                    function.name.clone(),
                    Signature {
                        parameters: function
                            .param_types
                            .iter()
                            .copied()
                            .map(Into::into)
                            .collect(),
                        result: function.return_type.into(),
                    },
                )
                .is_some()
            {
                return Err(TranslateError::new(
                    function.line,
                    format!("function '{}' is defined twice", function.name),
                ));
            }
        }
        let names = identifier_map(
            hir.ast
                .funcs
                .iter()
                .map(|function| function.name.as_str())
                .chain(hir.functions.iter().flat_map(|function| {
                    function
                        .bindings
                        .iter()
                        .map(|binding| binding.name.as_str())
                })),
            match target {
                TargetDialect::C => IdentifierTarget::C,
                TargetDialect::Cpp => IdentifierTarget::Cpp,
            },
        );
        Ok(Self {
            hir,
            signatures,
            names,
            out: String::new(),
            reserved: HashSet::new(),
            range_counter: 0,
            loop_depth: 0,
            target,
        })
    }

    fn emit(mut self) -> Result<String, TranslateError> {
        let target = if self.target == TargetDialect::C {
            "C"
        } else {
            "C++"
        };
        let _ = writeln!(
            self.out,
            "// Generated by the StudyRISC-V Rust-to-{target} translator."
        );
        self.out
            .push_str("// Compilable within the documented integer subset.\n\n");
        for function in &self.hir.ast.funcs {
            let _ = writeln!(self.out, "{};", self.signature(function));
        }
        self.out.push('\n');
        for (index, function) in self.hir.ast.funcs.iter().enumerate() {
            if index > 0 {
                self.out.push('\n');
            }
            self.emit_function(function)?;
        }
        Ok(self.out)
    }

    fn signature(&self, function: &Func) -> String {
        let parameters = function
            .params
            .iter()
            .zip(&function.param_types)
            .map(|(name, value_type)| {
                format!(
                    "{} {}",
                    self.target_type((*value_type).into()),
                    self.target_name(name)
                )
            })
            .collect::<Vec<_>>()
            .join(", ");
        format!(
            "{} {}({parameters})",
            self.target_type(function.return_type.into()),
            self.target_name(&function.name)
        )
    }

    fn emit_function(&mut self, function: &Func) -> Result<(), TranslateError> {
        self.reserved = self.names.values().cloned().collect();
        self.range_counter = 0;
        self.loop_depth = 0;
        let return_type: HirType = function.return_type.into();
        if return_type != HirType::Unit && block_flow(&function.body).falls_through {
            return Err(TranslateError::new(
                function.line,
                format!(
                    "function '{}' can fall through without returning {}",
                    function.name,
                    type_name(return_type)
                ),
            ));
        }
        let _ = writeln!(self.out, "{} {{", self.signature(function));
        self.emit_statements(function, &function.body, 1)?;
        match (self.target, return_type) {
            (TargetDialect::C, _) | (_, HirType::I32) => self.out.push_str("    return 0;\n"),
            (TargetDialect::Cpp, HirType::Bool) => self.out.push_str("    return false;\n"),
            (TargetDialect::Cpp, HirType::Unit) => {}
        }
        self.out.push_str("}\n");
        Ok(())
    }

    fn emit_statements(
        &mut self,
        function: &Func,
        statements: &[Stmt],
        depth: usize,
    ) -> Result<(), TranslateError> {
        for statement in statements {
            self.emit_statement(function, statement, depth)?;
        }
        Ok(())
    }

    fn emit_statement(
        &mut self,
        function: &Func,
        statement: &Stmt,
        depth: usize,
    ) -> Result<(), TranslateError> {
        let indent = "    ".repeat(depth);
        match statement {
            Stmt::Decl(name, initial, source, line) => {
                let initial = initial.as_ref().ok_or_else(|| {
                    TranslateError::new(*line, "Rust bindings require an initializer")
                })?;
                let expected = source
                    .declared_type
                    .map(Into::into)
                    .unwrap_or(self.binding_type(function, name, *line)?);
                if expected == HirType::Unit {
                    return Err(TranslateError::new(
                        *line,
                        "Rust subset bindings support only i32 and bool values, not unit",
                    ));
                }
                let actual = self.expression_type(function, initial)?;
                self.require_type(*line, expected, actual, "binding initializer")?;
                let value = self.expression(function, initial)?;
                let annotation = self.lookup_binding(function, name, *line)?.annotation;
                let name = self.target_name(name);
                let keyword = if self.target == TargetDialect::Cpp
                    && annotation == HirTypeAnnotation::Inferred
                {
                    "auto"
                } else {
                    self.target_type(expected)
                };
                let _ = writeln!(self.out, "{indent}{keyword} {name} = {value};");
            }
            Stmt::DeclArray(name, size, initial, _, initializer, line) => {
                let mut values = Vec::with_capacity(initial.len());
                for value in initial {
                    let actual = self.expression_type(function, value)?;
                    self.require_type(*line, HirType::I32, actual, "array initializer")?;
                    values.push(self.expression(function, value)?);
                }
                match initializer {
                    ArrayInitProvenance::Repeat => {
                        let value = values.first().ok_or_else(|| {
                            TranslateError::new(*line, "Rust repeat initializer is empty")
                        })?;
                        let temporary = self.fresh_range_name("repeat");
                        let _ = writeln!(self.out, "{indent}int {temporary} = {value};");
                        let repeated = vec![temporary; *size].join(", ");
                        let name = self.target_name(name);
                        let _ = writeln!(self.out, "{indent}int {name}[{size}] = {{{repeated}}};");
                    }
                    ArrayInitProvenance::List => {
                        let name = self.target_name(name);
                        let _ = writeln!(
                            self.out,
                            "{indent}int {name}[{size}] = {{{}}};",
                            values.join(", ")
                        );
                    }
                    ArrayInitProvenance::Absent => {
                        return Err(TranslateError::new(
                            *line,
                            "internal: Rust array declaration has no initializer",
                        ));
                    }
                }
            }
            Stmt::Expr(expression, _) => {
                self.expression_type(function, expression)?;
                let expression = self.expression(function, expression)?;
                let _ = writeln!(self.out, "{indent}{expression};");
            }
            Stmt::If(_, body, _, source) if source.origin == IfOrigin::PlainBlock => {
                let _ = writeln!(self.out, "{indent}{{");
                self.emit_statements(function, body, depth + 1)?;
                let _ = writeln!(self.out, "{indent}}}");
            }
            Stmt::If(condition, body, otherwise, _) => {
                self.require_condition(function, condition)?;
                let condition = self.expression(function, condition)?;
                let _ = writeln!(self.out, "{indent}if ({condition}) {{");
                self.emit_statements(function, body, depth + 1)?;
                if otherwise.is_empty() {
                    let _ = writeln!(self.out, "{indent}}}");
                } else {
                    let _ = writeln!(self.out, "{indent}}} else {{");
                    self.emit_statements(function, otherwise, depth + 1)?;
                    let _ = writeln!(self.out, "{indent}}}");
                }
            }
            Stmt::While(condition, body, source) => {
                if source.kind != LoopKind::RustLoop {
                    self.require_condition(function, condition)?;
                }
                let condition = if source.kind == LoopKind::RustLoop {
                    if self.target == TargetDialect::Cpp {
                        "true".to_string()
                    } else {
                        "1".to_string()
                    }
                } else {
                    self.expression(function, condition)?
                };
                let _ = writeln!(self.out, "{indent}while ({condition}) {{");
                self.loop_depth += 1;
                let body_result = self.emit_statements(function, body, depth + 1);
                self.loop_depth -= 1;
                body_result?;
                let _ = writeln!(self.out, "{indent}}}");
            }
            Stmt::For(initial, condition, _, body, source)
                if source.kind == LoopKind::RustRange =>
            {
                let (iterator, start, line) = range_start(initial)?;
                let end = range_end(condition, &iterator)?;
                self.require_type(
                    line,
                    HirType::I32,
                    self.expression_type(function, start)?,
                    "range start",
                )?;
                self.require_type(
                    line,
                    HirType::I32,
                    self.expression_type(function, end)?,
                    "range end",
                )?;
                let start_name = self.fresh_range_name("start");
                let end_name = self.fresh_range_name("end");
                let iterator = self.target_name(iterator);
                let start = self.expression(function, start)?;
                let end = self.expression(function, end)?;
                let _ = writeln!(self.out, "{indent}int {start_name} = {start};");
                let _ = writeln!(self.out, "{indent}int {end_name} = {end};");
                let _ = writeln!(
                    self.out,
                    "{indent}for (int {iterator} = {start_name}; {iterator} < {end_name}; {iterator} = {iterator} + 1) {{"
                );
                self.loop_depth += 1;
                let body_result = self.emit_statements(function, body, depth + 1);
                self.loop_depth -= 1;
                body_result?;
                let _ = writeln!(self.out, "{indent}}}");
            }
            Stmt::For(_, _, _, _, _) => {
                return Err(TranslateError::new(
                    0,
                    "internal: Rust AST contains a non-range for loop",
                ));
            }
            Stmt::Return(value, _, line) => {
                let expected = function.return_type.into();
                match value {
                    Some(value) => {
                        let actual = self.expression_type(function, value)?;
                        self.require_type(*line, expected, actual, "return value")?;
                        let value = self.expression(function, value)?;
                        let _ = writeln!(self.out, "{indent}return {value};");
                    }
                    None if expected == HirType::Unit => {
                        let value = if self.target == TargetDialect::Cpp {
                            "return;"
                        } else {
                            "return 0;"
                        };
                        let _ = writeln!(self.out, "{indent}{value}");
                    }
                    None => {
                        return Err(TranslateError::new(
                            *line,
                            "value-returning functions require a return value",
                        ));
                    }
                }
            }
            Stmt::Break(line) => {
                if self.loop_depth == 0 {
                    return Err(TranslateError::new(*line, "break outside a loop"));
                }
                let _ = writeln!(self.out, "{indent}break;");
            }
            Stmt::Continue(line) => {
                if self.loop_depth == 0 {
                    return Err(TranslateError::new(*line, "continue outside a loop"));
                }
                let _ = writeln!(self.out, "{indent}continue;");
            }
        }
        Ok(())
    }

    fn expression(&self, function: &Func, expression: &Expr) -> Result<String, TranslateError> {
        Ok(match expression {
            Expr::Num(value, value_type, _) => {
                if self.target == TargetDialect::Cpp && *value_type == super::ScalarType::Bool {
                    (*value != 0).to_string()
                } else {
                    value.to_string()
                }
            }
            Expr::Var(name, _) => self.target_name(name),
            Expr::Index(name, index, _) => {
                let index = match &**index {
                    Expr::Unary("as usize", value, _) => value,
                    _ => index,
                };
                format!(
                    "{}[{}]",
                    self.target_name(name),
                    self.expression(function, index)?
                )
            }
            Expr::Unary(operator, value, _) => {
                if *operator == "as usize" {
                    return self.expression(function, value);
                }
                let operator =
                    if *operator == "!" && self.expression_type(function, value)? == HirType::I32 {
                        "~"
                    } else {
                        operator
                    };
                format!("({operator}{})", self.expression(function, value)?)
            }
            Expr::Binary(operator, left, right, _) => {
                let rendered = format!(
                    "({} {operator} {})",
                    self.expression(function, left)?,
                    self.expression(function, right)?
                );
                if self.target == TargetDialect::Cpp
                    && matches!(*operator, "&" | "|" | "^")
                    && self.expression_type(function, expression)? == HirType::Bool
                {
                    format!("(!(!{rendered}))")
                } else {
                    rendered
                }
            }
            Expr::Assign(target, value, source, _) => {
                let target = self.lvalue(function, target)?;
                let value = self.expression(function, value)?;
                match source {
                    AssignmentProvenance::Simple => format!("({target} = {value})"),
                    AssignmentProvenance::Compound(operator) => {
                        format!("({target} {operator}= {value})")
                    }
                    AssignmentProvenance::PrefixIncrement
                    | AssignmentProvenance::PrefixDecrement
                    | AssignmentProvenance::PostfixIncrement
                    | AssignmentProvenance::PostfixDecrement => {
                        return Err(TranslateError::new(
                            expression_line(expression),
                            "internal: Rust AST contains C increment syntax",
                        ));
                    }
                }
            }
            Expr::Call(name, arguments, _) => format!(
                "{}({})",
                self.target_name(name),
                arguments
                    .iter()
                    .map(|argument| self.expression(function, argument))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ")
            ),
        })
    }

    fn lvalue(&self, function: &Func, target: &LValue) -> Result<String, TranslateError> {
        Ok(match target {
            LValue::Var(name, _) => self.target_name(name),
            LValue::Index(name, index, _) => {
                format!(
                    "{}[{}]",
                    self.target_name(name),
                    self.expression(function, index)?
                )
            }
        })
    }

    fn expression_type(
        &self,
        function: &Func,
        expression: &Expr,
    ) -> Result<HirType, TranslateError> {
        let line = expression_line(expression);
        match expression {
            Expr::Num(_, value_type, _) => Ok((*value_type).into()),
            Expr::Var(name, line) => self.lookup_type(function, name, *line),
            Expr::Index(name, index, line) => {
                self.lookup_array(function, name, *line)?;
                let index_type = match &**index {
                    Expr::Unary("as usize", value, _) => self.expression_type(function, value)?,
                    _ => self.expression_type(function, index)?,
                };
                self.require_type(*line, HirType::I32, index_type, "array index")?;
                Ok(HirType::I32)
            }
            Expr::Unary(operator, value, _) => {
                let value_type = self.expression_type(function, value)?;
                match *operator {
                    "as usize" => Err(type_error(
                        line,
                        "'as usize' casts are only supported directly inside array indexes",
                    )),
                    "-" | "~" => {
                        self.require_type(line, HirType::I32, value_type, "unary operand")?;
                        Ok(HirType::I32)
                    }
                    "!" if matches!(value_type, HirType::I32 | HirType::Bool) => Ok(value_type),
                    _ => Err(type_error(line, "unsupported unary operand type")),
                }
            }
            Expr::Binary(operator, left, right, _) => {
                let left_type = self.expression_type(function, left)?;
                let right_type = self.expression_type(function, right)?;
                match *operator {
                    "&&" | "||" => {
                        self.require_pair(line, HirType::Bool, left_type, right_type)?;
                        Ok(HirType::Bool)
                    }
                    "==" | "!=" => {
                        self.require_type(line, left_type, right_type, "comparison operand")?;
                        Ok(HirType::Bool)
                    }
                    "<" | "<=" | ">" | ">=" => {
                        self.require_pair(line, HirType::I32, left_type, right_type)?;
                        Ok(HirType::Bool)
                    }
                    "&" | "|" | "^" if left_type == right_type => Ok(left_type),
                    "+" | "-" | "*" | "/" | "%" | "<<" | ">>" | "&" | "|" | "^" => {
                        self.require_pair(line, HirType::I32, left_type, right_type)?;
                        Ok(HirType::I32)
                    }
                    _ => Err(type_error(line, "unsupported binary operand types")),
                }
            }
            Expr::Assign(target, value, _, _) => {
                let target_type = self.lvalue_type(function, target)?;
                let value_type = self.expression_type(function, value)?;
                self.require_type(line, target_type, value_type, "assignment")?;
                Ok(HirType::Unit)
            }
            Expr::Call(name, arguments, line) => {
                let signature = self.signatures.get(name).ok_or_else(|| {
                    TranslateError::new(*line, format!("call to undefined function '{name}'"))
                })?;
                if arguments.len() != signature.parameters.len() {
                    return Err(TranslateError::new(
                        *line,
                        format!(
                            "function '{name}' expects {} arguments, found {}",
                            signature.parameters.len(),
                            arguments.len()
                        ),
                    ));
                }
                for (argument, expected) in arguments.iter().zip(&signature.parameters) {
                    let actual = self.expression_type(function, argument)?;
                    self.require_type(*line, *expected, actual, "function argument")?;
                }
                Ok(signature.result)
            }
        }
    }

    fn lvalue_type(&self, function: &Func, target: &LValue) -> Result<HirType, TranslateError> {
        match target {
            LValue::Var(name, line) => self.lookup_type(function, name, *line),
            LValue::Index(name, index, line) => {
                self.lookup_array(function, name, *line)?;
                let index_type = match index {
                    Expr::Unary("as usize", value, _) => self.expression_type(function, value)?,
                    _ => self.expression_type(function, index)?,
                };
                self.require_type(*line, HirType::I32, index_type, "array index")?;
                Ok(HirType::I32)
            }
        }
    }

    fn require_condition(&self, function: &Func, condition: &Expr) -> Result<(), TranslateError> {
        let actual = self.expression_type(function, condition)?;
        self.require_type(
            expression_line(condition),
            HirType::Bool,
            actual,
            "condition",
        )
    }

    fn require_pair(
        &self,
        line: usize,
        expected: HirType,
        left: HirType,
        right: HirType,
    ) -> Result<(), TranslateError> {
        self.require_type(line, expected, left, "left operand")?;
        self.require_type(line, expected, right, "right operand")
    }

    fn require_type(
        &self,
        line: usize,
        expected: HirType,
        actual: HirType,
        context: &str,
    ) -> Result<(), TranslateError> {
        if expected == actual {
            Ok(())
        } else {
            Err(TranslateError::new(
                line,
                format!(
                    "invalid Rust subset type: {context} requires {}, found {}",
                    type_name(expected),
                    type_name(actual)
                ),
            ))
        }
    }

    fn lookup_type(
        &self,
        function: &Func,
        name: &str,
        line: usize,
    ) -> Result<HirType, TranslateError> {
        let binding = self.lookup_binding(function, name, line)?;
        if binding.array_len.is_some() {
            return Err(TranslateError::new(
                line,
                format!(
                    "'{name}' is an array and can only be used with an index; arrays can only be indexed here"
                ),
            ));
        }
        Ok(binding.value_type)
    }

    fn lookup_array(&self, function: &Func, name: &str, line: usize) -> Result<(), TranslateError> {
        if self
            .lookup_binding(function, name, line)?
            .array_len
            .is_none()
        {
            return Err(TranslateError::new(
                line,
                format!("'{name}' is not an array"),
            ));
        }
        Ok(())
    }

    fn lookup_binding(
        &self,
        function: &Func,
        name: &str,
        line: usize,
    ) -> Result<&HirBinding, TranslateError> {
        self.function_hir(&function.name)
            .bindings
            .iter()
            .find(|binding| binding.name == name)
            .ok_or_else(|| TranslateError::new(line, format!("binding '{name}' is not declared")))
    }

    fn binding_type(
        &self,
        function: &Func,
        name: &str,
        line: usize,
    ) -> Result<HirType, TranslateError> {
        Ok(self.lookup_binding(function, name, line)?.value_type)
    }

    fn function_hir(&self, name: &str) -> &HirFunction {
        self.hir
            .functions
            .iter()
            .find(|function| function.name == name)
            .expect("HIR function must match AST")
    }

    fn fresh_range_name(&mut self, role: &str) -> String {
        loop {
            let name = format!("riscvsim_range_{role}_{}", self.range_counter);
            self.range_counter += 1;
            if self.reserved.insert(name.clone()) {
                return name;
            }
        }
    }

    fn target_name(&self, name: &str) -> String {
        self.names
            .get(name)
            .cloned()
            .unwrap_or_else(|| name.to_string())
    }

    fn target_type(&self, value_type: HirType) -> &'static str {
        match (self.target, value_type) {
            (TargetDialect::Cpp, HirType::Bool) => "bool",
            (TargetDialect::Cpp, HirType::Unit) => "void",
            _ => "int",
        }
    }
}

#[derive(Clone, Copy)]
struct Flow {
    falls_through: bool,
    breaks_current_loop: bool,
}

fn block_flow(statements: &[Stmt]) -> Flow {
    let mut flow = Flow {
        falls_through: true,
        breaks_current_loop: false,
    };
    for statement in statements {
        if !flow.falls_through {
            break;
        }
        let statement = statement_flow(statement);
        flow.breaks_current_loop |= statement.breaks_current_loop;
        flow.falls_through = statement.falls_through;
    }
    flow
}

fn statement_flow(statement: &Stmt) -> Flow {
    match statement {
        Stmt::Return(..) => Flow {
            falls_through: false,
            breaks_current_loop: false,
        },
        Stmt::Break(_) => Flow {
            falls_through: false,
            breaks_current_loop: true,
        },
        Stmt::Continue(_) => Flow {
            falls_through: false,
            breaks_current_loop: false,
        },
        Stmt::If(_, body, _, source) if source.origin == IfOrigin::PlainBlock => block_flow(body),
        Stmt::If(_, body, otherwise, _) => {
            let then_flow = block_flow(body);
            let else_flow = if otherwise.is_empty() {
                Flow {
                    falls_through: true,
                    breaks_current_loop: false,
                }
            } else {
                block_flow(otherwise)
            };
            Flow {
                falls_through: then_flow.falls_through || else_flow.falls_through,
                breaks_current_loop: then_flow.breaks_current_loop || else_flow.breaks_current_loop,
            }
        }
        Stmt::While(_, body, source) if source.kind == LoopKind::RustLoop => Flow {
            falls_through: block_flow(body).breaks_current_loop,
            breaks_current_loop: false,
        },
        Stmt::While(..) | Stmt::For(..) => Flow {
            falls_through: true,
            breaks_current_loop: false,
        },
        Stmt::Decl(..) | Stmt::DeclArray(..) | Stmt::Expr(..) => Flow {
            falls_through: true,
            breaks_current_loop: false,
        },
    }
}

fn range_start(initial: &Option<Box<Stmt>>) -> Result<(&str, &Expr, usize), TranslateError> {
    match initial.as_deref() {
        Some(Stmt::Decl(name, Some(start), _, line)) => Ok((name, start, *line)),
        _ => Err(TranslateError::new(
            0,
            "internal: malformed Rust range initializer",
        )),
    }
}

fn range_end<'a>(condition: &'a Option<Expr>, iterator: &str) -> Result<&'a Expr, TranslateError> {
    match condition {
        Some(Expr::Binary("<", left, end, _)) if matches!(&**left, Expr::Var(name, _) if name == iterator) => {
            Ok(end)
        }
        _ => Err(TranslateError::new(
            0,
            "internal: malformed Rust range condition",
        )),
    }
}

fn expression_line(expression: &Expr) -> usize {
    match expression {
        Expr::Var(_, line) | Expr::Index(_, _, line) | Expr::Call(_, _, line) => *line,
        Expr::Num(_, _, line)
        | Expr::Unary(_, _, line)
        | Expr::Binary(_, _, _, line)
        | Expr::Assign(_, _, _, line) => *line,
    }
}

fn type_name(value_type: HirType) -> &'static str {
    match value_type {
        HirType::I32 => "i32",
        HirType::Bool => "bool",
        HirType::Unit => "unit",
    }
}

fn type_error(line: usize, message: &str) -> TranslateError {
    TranslateError::new(line, format!("invalid Rust subset type: {message}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        assemble, assemble64, c_to_asm, cpp_to_asm, cpp_to_asm64, rust_to_asm, rust_to_asm64,
        Pipeline, Pipeline64,
    };

    fn run_assembly(assembly: &str) -> i32 {
        let program = assemble(assembly).unwrap_or_else(|error| {
            panic!("generated assembly did not assemble: {error:?}\n{assembly}")
        });
        let mut pipeline = Pipeline::new(program);
        assert!(pipeline.run(1_000_000), "program did not halt:\n{assembly}");
        pipeline.snapshot().registers[10] as i32
    }

    fn run_rust(source: &str) -> i32 {
        run_assembly(&rust_to_asm(source).expect("Rust source did not compile"))
    }

    fn run_assembly64(assembly: &str) -> i32 {
        let program = assemble64(assembly).unwrap_or_else(|errors| {
            panic!("generated RV64 did not assemble: {errors:?}\n{assembly}")
        });
        let mut pipeline = Pipeline64::new(program);
        assert!(
            pipeline.run(1_000_000),
            "RV64 program did not halt:\n{assembly}"
        );
        let halt = pipeline.snapshot().halt.expect("missing RV64 halt state");
        assert_eq!(halt.kind, "complete", "RV64 trapped: {}", halt.message);
        pipeline.registers()[10] as u32 as i32
    }

    fn run_rust64(source: &str) -> i32 {
        run_assembly64(&rust_to_asm64(source).expect("Rust source did not compile for RV64"))
    }

    fn run_cpp(source: &str) -> i32 {
        run_assembly(&cpp_to_asm(source).expect("translated C++ did not compile"))
    }

    fn run_cpp64(source: &str) -> i32 {
        run_assembly64(&cpp_to_asm64(source).expect("translated C++ did not compile for RV64"))
    }

    fn run_c(source: &str) -> i32 {
        run_assembly(&c_to_asm(source).expect("translated C did not compile"))
    }

    fn assert_round_trip(source: &str) -> String {
        let translated = translate(source).expect("Rust-to-C translation failed");
        let tokens = super::super::lex(&translated).expect("translated C did not lex");
        super::super::Parser::new(tokens)
            .parse_unit()
            .expect("translated C did not reparse");
        assert_eq!(run_c(&translated), run_rust(source), "{translated}");
        translated
    }

    fn assert_cpp_round_trip(source: &str) -> String {
        let translated = translate_cpp(source).unwrap_or_else(|error| {
            panic!(
                "Rust-to-C++ translation failed at line {}: {}",
                error.line, error.message
            )
        });
        super::super::parse_cpp_unit(&translated).unwrap_or_else(|error| {
            panic!(
                "translated C++ did not reparse at line {}: {}\n{translated}",
                error.line, error.message
            )
        });
        assert_eq!(run_cpp(&translated), run_rust(source), "{translated}");
        assert_eq!(run_cpp64(&translated), run_rust64(source), "{translated}");
        translated
    }

    #[test]
    fn rust_to_c_representative_output_is_byte_identical() {
        let source = "fn ready(value: i32) -> bool { return value > 0; }
                      fn main() -> i32 {
                          let flag = ready(2);
                          if flag { return 7; }
                          return 0;
                      }";
        assert_eq!(
            translate(source).unwrap(),
            concat!(
                "// Generated by the StudyRISC-V Rust-to-C translator.\n",
                "// Compilable within the documented integer subset.\n\n",
                "int ready(int value);\n",
                "int main();\n\n",
                "int ready(int value) {\n",
                "    return (value > 0);\n",
                "    return 0;\n",
                "}\n\n",
                "int main() {\n",
                "    int flag = ready(2);\n",
                "    if (flag) {\n",
                "        return 7;\n",
                "    }\n",
                "    return 0;\n",
                "    return 0;\n",
                "}\n",
            )
        );
    }

    #[test]
    fn rust_to_c_scalars_booleans_and_tail_expressions_execute_equivalently() {
        assert_round_trip(
            "fn choose(value: i32, enabled: bool) -> i32 {
                let threshold = 4;
                if enabled && value > threshold { return value + 2; } else { return threshold; }
            }
            fn main() -> i32 { return choose(5, true); }",
        );
    }

    #[test]
    fn rust_to_c_recursion_and_forward_calls_execute_equivalently() {
        let translated = assert_round_trip(
            "fn main() -> i32 { return factorial(5); }
             fn factorial(value: i32) -> i32 {
                 if value <= 1 { return 1; }
                 return value * factorial(value - 1);
             }",
        );
        assert!(translated.contains("int factorial(int value);"));
        assert!(
            translated.find("int factorial(int value);").unwrap()
                < translated.find("int main() {").unwrap()
        );
    }

    #[test]
    fn rust_to_c_renames_c_keywords_and_avoids_generated_name_collisions() {
        let translated = assert_round_trip(
            "fn auto(register: i32) -> i32 {
                let mut switch = register;
                switch += 1;
                switch
            }
            fn riscvsim_auto(value: i32) -> i32 { value }
            fn main() -> i32 { auto(6) + riscvsim_auto(1) }",
        );
        assert!(translated.contains("int riscvsim_auto_1(int riscvsim_register)"));
        assert!(translated.contains("int riscvsim_switch = riscvsim_register;"));
        assert!(translated.contains("riscvsim_auto_1(6)"));
        assert_eq!(run_c(&translated), 8);
    }

    #[test]
    fn rust_to_c_arrays_execute_equivalently() {
        assert_round_trip(
            "fn main() -> i32 {
                let mut values: [i32; 4] = [1, 2, 3, 4];
                values[2] = values[0] + values[3];
                return values[1] + values[2];
            }",
        );
    }

    #[test]
    fn rust_to_c_usize_array_index_cast_executes_equivalently() {
        let translated = assert_round_trip(
            "fn main() -> i32 {
                let values = [2, 4, 8];
                let index: i32 = 2;
                return values[(index as usize)];
            }",
        );
        assert!(translated.contains("values[index]"), "{translated}");
    }

    #[test]
    fn rust_to_c_while_loop_and_loop_control_execute_equivalently() {
        assert_round_trip(
            "fn main() -> i32 {
                let mut value = 0;
                while value < 8 {
                    value += 1;
                    if value == 2 { continue; }
                    if value == 5 { break; }
                }
                loop { value += 3; break; }
                return value;
            }",
        );
    }

    #[test]
    fn rust_to_c_ranges_execute_equivalently_and_snapshot_bounds() {
        let translated = assert_round_trip(
            "fn main() -> i32 {
                let end = 5;
                let mut sum = 0;
                for value in 1..end { sum += value; }
                return sum;
            }",
        );
        assert!(translated.contains("riscvsim_range_start_"));
        assert!(translated.contains("riscvsim_range_end_"));
    }

    #[test]
    fn rust_to_c_mutable_range_bound_uses_rust_snapshot_semantics() {
        let source = "fn main() -> i32 {
                let mut end = 4;
                let mut count = 0;
                for value in 0..end { count += 1; end = value; }
                return count;
            }";
        let translated = assert_round_trip(source);
        assert_eq!(run_rust(source), 4);
        assert_eq!(run_c(&translated), 4, "{translated}");
    }

    #[test]
    fn rust_to_c_repeat_arrays_evaluate_initializer_once_and_execute_equivalently() {
        let translated = assert_round_trip(
            "fn seed() -> i32 { return 6; }
             fn main() -> i32 {
                 let values = [seed(); 3];
                 return values[0] + values[1] + values[2];
             }",
        );
        assert_eq!(translated.matches("= seed();").count(), 1, "{translated}");
    }

    #[test]
    fn rust_to_c_boolean_functions_execute_equivalently() {
        assert_round_trip(
            "fn less(left: i32, right: i32) -> bool { return left < right; }
             fn main() -> i32 {
                 let both = less(2, 3) & !less(5, 4);
                 if both { return 9; }
                 return 0;
             }",
        );
    }

    #[test]
    fn rust_to_c_nested_ranges_use_distinct_snapshots_and_execute_equivalently() {
        let translated = assert_round_trip(
            "fn main() -> i32 {
                 let mut total = 0;
                 for outer in 0..2 {
                     for inner in 1..3 { total += outer + inner; }
                 }
                 return total;
             }",
        );
        assert!(translated.contains("riscvsim_range_end_1"), "{translated}");
        assert!(translated.contains("riscvsim_range_end_3"), "{translated}");
    }

    #[test]
    fn rust_to_c_unit_functions_return_zero_in_c() {
        assert_round_trip(
            "fn touch(value: i32) { let copy = value; }
             fn main() -> i32 { touch(3); return 7; }",
        );
    }

    #[test]
    fn rust_to_c_preserves_boolean_and_integer_not_distinction() {
        let translated = translate(
            "fn main() -> i32 {
                let flag = !true;
                let mask = !1;
                if flag { return 0; }
                return mask;
            }",
        )
        .unwrap();
        assert!(translated.contains("int flag = (!1);"));
        assert!(translated.contains("int mask = (~1);"));
        assert_eq!(run_c(&translated), -2);
    }

    #[test]
    fn rust_to_c_rejects_integer_conditions() {
        let error = translate("fn main() -> i32 { if 1 { return 1; } return 0; }").unwrap_err();
        assert!(error.message.contains("condition requires bool, found i32"));
    }

    #[test]
    fn rust_to_c_rejects_mismatched_declared_types() {
        let error = translate("fn main() -> i32 { let flag: bool = 1; return 0; }").unwrap_err();
        assert!(error
            .message
            .contains("binding initializer requires bool, found i32"));
    }

    #[test]
    fn rust_to_c_rejects_mismatched_function_arguments() {
        let error = translate(
            "fn enabled(flag: bool) -> i32 { if flag { return 1; } return 0; }
             fn main() -> i32 { return enabled(1); }",
        )
        .unwrap_err();
        assert!(error
            .message
            .contains("function argument requires bool, found i32"));
    }

    #[test]
    fn rust_to_c_rejects_value_producing_assignments() {
        let error =
            translate("fn main() -> i32 { let mut value = 0; return value = 3; }").unwrap_err();
        assert!(error
            .message
            .contains("assignment expressions have unit value"));
    }

    #[test]
    fn rust_to_c_rejects_indexing_a_scalar() {
        let error = translate("fn main() -> i32 { let value = 3; return value[0]; }").unwrap_err();
        assert_eq!(error.line, 1);
        assert!(error.message.contains("'value' is not an array"));
    }

    #[test]
    fn rust_to_c_rejects_using_an_array_as_a_scalar() {
        let error =
            translate("fn main() -> i32 { let values = [1, 2]; return values; }").unwrap_err();
        assert_eq!(error.line, 1);
        assert!(error
            .message
            .contains("'values' is an array and can only be used with an index"));
    }

    #[test]
    fn rust_to_c_rejects_unit_valued_bindings() {
        let error = translate(
            "fn touch() { return; }
             fn main() -> i32 { let result = touch(); return 0; }",
        )
        .unwrap_err();
        assert_eq!(error.line, 2);
        assert!(error.message.contains("not unit"));
    }

    #[test]
    fn rust_to_c_rejects_duplicate_function_definitions() {
        let error = translate(
            "fn helper() -> i32 { return 1; }
             fn helper() -> i32 { return 2; }
             fn main() -> i32 { return helper(); }",
        )
        .unwrap_err();
        assert_eq!(error.line, 2);
        assert!(error.message.contains("defined twice"));
    }

    #[test]
    fn rust_to_c_rejects_loop_control_outside_a_loop() {
        let break_error = translate("fn main() -> i32 { break; return 0; }").unwrap_err();
        assert!(break_error.message.contains("break outside a loop"));
        let continue_error = translate("fn main() -> i32 { continue; return 0; }").unwrap_err();
        assert!(continue_error.message.contains("continue outside a loop"));
    }

    #[test]
    fn rust_to_c_rejects_undefined_function_calls() {
        let error = translate("fn main() -> i32 { return missing(1); }").unwrap_err();
        assert!(error.message.contains("undefined function 'missing'"));
    }

    #[test]
    fn rust_to_c_rejects_wrong_function_arity() {
        let error = translate(
            "fn identity(value: i32) -> i32 { return value; }
             fn main() -> i32 { return identity(1, 2); }",
        )
        .unwrap_err();
        assert!(error.message.contains("expects 1 arguments, found 2"));
    }

    #[test]
    fn rust_to_c_rejects_boolean_array_indexes() {
        let error = translate(
            "fn main() -> i32 { let values = [3, 4]; let index = true; return values[index]; }",
        )
        .unwrap_err();
        assert!(error
            .message
            .contains("array index requires i32, found bool"));
    }

    #[test]
    fn rust_to_c_rejects_boolean_arithmetic() {
        let error =
            translate("fn main() -> i32 { let value = true + 1; return value; }").unwrap_err();
        assert!(error
            .message
            .contains("left operand requires i32, found bool"));
    }

    #[test]
    fn rust_to_cpp_emits_native_signatures_and_safe_auto_storage() {
        let translated = assert_cpp_round_trip(
            "fn ready(value: i32) -> bool { return value > 0; }
             fn main() -> i32 {
                 let inferred = ready(3);
                 let declared: bool = inferred;
                 if declared { return 7; }
                 return 0;
             }",
        );
        assert!(
            translated.contains("bool ready(int value);"),
            "{translated}"
        );
        assert!(
            translated.contains("auto inferred = ready(3);"),
            "{translated}"
        );
        assert!(
            translated.contains("bool declared = inferred;"),
            "{translated}"
        );
    }

    #[test]
    fn rust_to_cpp_boolean_literals_logical_ops_and_comparisons_execute() {
        let translated = assert_cpp_round_trip(
            "fn main() -> i32 {
                 let first = true;
                 let second = false;
                 let ready = first && !second && 2 < 3;
                 if ready { return 9; }
                 return 0;
             }",
        );
        assert!(translated.contains("auto first = true;"), "{translated}");
        assert!(translated.contains("auto second = false;"), "{translated}");
    }

    #[test]
    fn rust_to_cpp_boolean_bitwise_results_retain_boolean_auto_type() {
        let translated = assert_cpp_round_trip(
            "fn main() -> i32 {
                 let left = true;
                 let right = false;
                 let both = (left | right) ^ false;
                 if both { return 6; }
                 return 0;
             }",
        );
        assert!(translated.contains("auto both = (!(!"), "{translated}");
    }

    #[test]
    fn rust_to_cpp_integer_not_remains_bitwise_not() {
        let translated = assert_cpp_round_trip("fn main() -> i32 { let mask = !1; return mask; }");
        assert!(translated.contains("auto mask = (~1);"), "{translated}");
    }

    #[test]
    fn rust_to_cpp_mutable_locals_parameters_and_assignments_execute() {
        assert_cpp_round_trip(
            "fn advance(mut value: i32) -> i32 {
                 value += 2;
                 value = value * 3;
                 return value;
             }
             fn main() -> i32 { let mut value = 1; value += advance(2); return value; }",
        );
    }

    #[test]
    fn rust_to_cpp_forward_calls_and_recursion_execute() {
        let translated = assert_cpp_round_trip(
            "fn main() -> i32 { return factorial(5); }
             fn factorial(value: i32) -> i32 {
                 if value <= 1 { return 1; }
                 return value * factorial(value - 1);
             }",
        );
        assert!(
            translated.find("int factorial(int value);").unwrap()
                < translated.find("int main() {").unwrap(),
            "{translated}"
        );
    }

    #[test]
    fn rust_to_cpp_unit_functions_emit_void_and_execute() {
        let translated = assert_cpp_round_trip(
            "fn touch(value: i32) { let copy = value; }
             fn main() -> i32 { touch(3); return 7; }",
        );
        assert!(
            translated.contains("void touch(int value);"),
            "{translated}"
        );
        assert!(
            translated.contains("void touch(int value) {"),
            "{translated}"
        );
    }

    #[test]
    fn rust_to_cpp_array_lists_and_mutation_execute() {
        assert_cpp_round_trip(
            "fn main() -> i32 {
                 let mut values: [i32; 4] = [1, 2, 3, 4];
                 values[2] = values[0] + values[3];
                 return values[1] + values[2];
             }",
        );
    }

    #[test]
    fn rust_to_cpp_repeat_arrays_emit_one_initializer_evaluation() {
        let translated = assert_cpp_round_trip(
            "fn seed() -> i32 { return 6; }
             fn main() -> i32 {
                 let values = [seed(); 3];
                 return values[0] + values[1] + values[2];
             }",
        );
        assert_eq!(translated.matches("= seed();").count(), 1, "{translated}");
    }

    #[test]
    fn rust_to_cpp_usize_index_cast_is_erased_and_executes() {
        let translated = assert_cpp_round_trip(
            "fn main() -> i32 {
                 let values = [2, 4, 8];
                 let index: i32 = 2;
                 return values[index as usize];
             }",
        );
        assert!(translated.contains("values[index]"), "{translated}");
        assert!(!translated.contains("usize"), "{translated}");
    }

    #[test]
    fn rust_to_cpp_range_loops_snapshot_bounds_and_execute() {
        let translated = assert_cpp_round_trip(
            "fn main() -> i32 {
                 let end = 5;
                 let mut sum = 0;
                 for value in 1..end { sum += value; }
                 return sum;
             }",
        );
        assert!(translated.contains("riscvsim_range_start_"), "{translated}");
        assert!(translated.contains("riscvsim_range_end_"), "{translated}");
    }

    #[test]
    fn rust_to_cpp_mutable_range_bounds_use_snapshot_semantics() {
        let source = "fn main() -> i32 {
                let mut end = 4;
                let mut count = 0;
                for value in 0..end { count += 1; end = value; }
                return count;
            }";
        let translated = assert_cpp_round_trip(source);
        assert_eq!(run_rust(source), 4);
        assert_eq!(run_cpp(&translated), 4, "{translated}");
        assert_eq!(run_cpp64(&translated), 4, "{translated}");
    }

    #[test]
    fn rust_to_cpp_nested_ranges_use_distinct_snapshots() {
        let translated = assert_cpp_round_trip(
            "fn main() -> i32 {
                 let mut total = 0;
                 for outer in 0..2 {
                     for inner in 1..3 { total += outer + inner; }
                 }
                 return total;
             }",
        );
        assert!(translated.contains("riscvsim_range_end_1"), "{translated}");
        assert!(translated.contains("riscvsim_range_end_3"), "{translated}");
    }

    #[test]
    fn rust_to_cpp_while_break_and_continue_execute() {
        assert_cpp_round_trip(
            "fn main() -> i32 {
                 let mut value = 0;
                 while value < 8 {
                     value += 1;
                     if value == 2 { continue; }
                     if value == 5 { break; }
                 }
                 return value;
             }",
        );
    }

    #[test]
    fn rust_to_cpp_loop_uses_true_and_breaks_cleanly() {
        let translated = assert_cpp_round_trip(
            "fn main() -> i32 {
                 let mut value = 1;
                 loop { value += 2; if value > 5 { break; } }
                 return value;
             }",
        );
        assert!(translated.contains("while (true)"), "{translated}");
    }

    #[test]
    fn rust_to_cpp_tail_expressions_execute_as_returns() {
        assert_cpp_round_trip(
            "fn choose(value: i32) -> i32 {
                 if value > 3 { return value + 1; }
                 value - 1
             }
             fn main() -> i32 { choose(5) + choose(2) }",
        );
    }

    #[test]
    fn rust_to_cpp_plain_blocks_and_if_else_execute() {
        assert_cpp_round_trip(
            "fn main() -> i32 {
                 let mut value = 2;
                 { value += 3; }
                 if value > 4 { value *= 2; } else { value = 0; }
                 return value;
             }",
        );
    }

    #[test]
    fn rust_to_cpp_integer_operator_surface_executes() {
        assert_cpp_round_trip(
            "fn main() -> i32 {
                 let value = 29;
                 let mixed = ((value % 6) << 3) | ((value / 4) ^ 2);
                 return mixed + (!0 & 3);
             }",
        );
    }

    #[test]
    fn rust_to_cpp_target_keywords_are_renamed_consistently() {
        let translated = assert_cpp_round_trip(
            "fn auto(class: i32) -> i32 {
                 let mut and = class;
                 and += 1;
                 return and;
             }
             fn riscvsim_auto(value: i32) -> i32 { return value; }
             fn main() -> i32 { return auto(6) + riscvsim_auto(1); }",
        );
        assert!(!translated.contains("int auto("), "{translated}");
        assert!(!translated.contains("int class"), "{translated}");
    }

    #[test]
    fn rust_to_cpp_bool_arguments_and_returns_stay_native() {
        let translated = assert_cpp_round_trip(
            "fn ready(value: i32) -> bool { return value != 0; }
             fn choose(enabled: bool) -> i32 {
                 if enabled { return 8; }
                 return 3;
             }
             fn main() -> i32 { return choose(ready(7)); }",
        );
        assert!(
            translated.contains("int choose(bool enabled);"),
            "{translated}"
        );
    }

    #[test]
    fn rust_to_cpp_unit_calls_remain_expression_statements() {
        let translated = assert_cpp_round_trip(
            "fn touch() { return; }
             fn main() -> i32 { touch(); touch(); return 5; }",
        );
        assert_eq!(
            translated.matches("\n    touch();").count(),
            2,
            "{translated}"
        );
    }

    #[test]
    fn rust_to_cpp_range_iterators_can_index_arrays() {
        assert_cpp_round_trip(
            "fn main() -> i32 {
                 let values = [2, 4, 6, 8];
                 let mut total = 0;
                 for index in 0..4 { total += values[index as usize]; }
                 return total;
             }",
        );
    }

    #[test]
    fn rust_to_cpp_explicit_and_inferred_integer_bindings_remain_distinct() {
        let translated = assert_cpp_round_trip(
            "fn main() -> i32 {
                 let inferred = 3;
                 let declared: i32 = 4;
                 return inferred + declared;
             }",
        );
        assert!(translated.contains("auto inferred = 3;"), "{translated}");
        assert!(translated.contains("int declared = 4;"), "{translated}");
    }

    #[test]
    fn rust_to_cpp_bare_unit_returns_emit_native_return() {
        let translated = assert_cpp_round_trip(
            "fn touch(value: i32) { if value > 0 { return; } return; }
             fn main() -> i32 { touch(2); return 4; }",
        );
        assert!(translated.contains("return;"), "{translated}");
        assert!(!translated.contains("void touch(int value) {\n    return 0;"));
    }

    #[test]
    fn rust_to_cpp_comparison_equality_and_boolean_not_execute() {
        assert_cpp_round_trip(
            "fn main() -> i32 {
                 let first = 3 == 3;
                 let second = 4 != 4;
                 if first && !second { return 11; }
                 return 0;
             }",
        );
    }

    #[test]
    fn rust_to_cpp_rejects_integer_conditions() {
        let error = translate_cpp("fn main() -> i32 { if 1 { return 1; } return 0; }")
            .expect_err("integer condition must be rejected");
        assert!(error.message.contains("condition requires bool, found i32"));
    }

    #[test]
    fn rust_to_cpp_rejects_binding_and_return_type_mismatches() {
        let binding = translate_cpp("fn main() -> i32 { let flag: bool = 1; return 0; }")
            .expect_err("binding mismatch must be rejected");
        assert!(binding
            .message
            .contains("binding initializer requires bool, found i32"));
        let returned =
            translate_cpp("fn ready() -> bool { return 1; } fn main() -> i32 { return 0; }")
                .expect_err("return mismatch must be rejected");
        assert!(returned
            .message
            .contains("return value requires bool, found i32"));
    }

    #[test]
    fn rust_to_cpp_rejects_argument_type_and_arity_mismatches() {
        let typed = translate_cpp(
            "fn choose(flag: bool) -> i32 { if flag { return 1; } return 0; }
             fn main() -> i32 { return choose(1); }",
        )
        .expect_err("argument type mismatch must be rejected");
        assert!(typed
            .message
            .contains("function argument requires bool, found i32"));
        let arity = translate_cpp(
            "fn identity(value: i32) -> i32 { return value; }
             fn main() -> i32 { return identity(1, 2); }",
        )
        .expect_err("wrong arity must be rejected");
        assert!(arity.message.contains("expects 1 arguments, found 2"));
    }

    #[test]
    fn rust_to_cpp_rejects_unit_valued_bindings() {
        let error = translate_cpp(
            "fn touch() { return; }
             fn main() -> i32 { let result = touch(); return 0; }",
        )
        .expect_err("unit binding must be rejected");
        assert!(error.message.contains("not unit"));
    }

    #[test]
    fn rust_to_cpp_rejects_duplicate_and_undefined_functions() {
        let duplicate = translate_cpp(
            "fn helper() -> i32 { return 1; }
             fn helper() -> i32 { return 2; }
             fn main() -> i32 { return helper(); }",
        )
        .expect_err("duplicate function must be rejected");
        assert!(duplicate.message.contains("defined twice"));
        let undefined = translate_cpp("fn main() -> i32 { return missing(1); }")
            .expect_err("undefined function must be rejected");
        assert!(undefined.message.contains("undefined function 'missing'"));
    }

    #[test]
    fn rust_to_cpp_rejects_loop_control_outside_loops() {
        let broken = translate_cpp("fn main() -> i32 { break; return 0; }")
            .expect_err("break outside loop must be rejected");
        assert!(broken.message.contains("break outside a loop"));
        let continued = translate_cpp("fn main() -> i32 { continue; return 0; }")
            .expect_err("continue outside loop must be rejected");
        assert!(continued.message.contains("continue outside a loop"));
    }

    #[test]
    fn rust_to_cpp_rejects_scalar_and_array_category_misuse() {
        let scalar = translate_cpp("fn main() -> i32 { let value = 3; return value[0]; }")
            .expect_err("indexing scalar must be rejected");
        assert!(scalar.message.contains("'value' is not an array"));
        let array = translate_cpp("fn main() -> i32 { let values = [1, 2]; return values; }")
            .expect_err("array-as-scalar must be rejected");
        assert!(array.message.contains("'values' is an array"));
    }

    #[test]
    fn rust_to_cpp_rejects_boolean_indexes_and_arithmetic() {
        let index = translate_cpp(
            "fn main() -> i32 { let values = [3, 4]; let index = true; return values[index]; }",
        )
        .expect_err("boolean index must be rejected");
        assert!(index
            .message
            .contains("array index requires i32, found bool"));
        let arithmetic = translate_cpp("fn main() -> i32 { let value = true + 1; return value; }")
            .expect_err("boolean arithmetic must be rejected");
        assert!(arithmetic
            .message
            .contains("left operand requires i32, found bool"));
    }

    #[test]
    fn rust_to_cpp_rejects_value_functions_that_can_fall_through() {
        let error = translate_cpp(
            "fn helper() -> i32 { let value = 1; }
             fn main() -> i32 { return helper(); }",
        )
        .expect_err("fallthrough value function must be rejected");
        assert!(error
            .message
            .contains("can fall through without returning i32"));
    }

    #[test]
    fn rust_to_cpp_rejects_value_producing_assignments() {
        let error = translate_cpp("fn main() -> i32 { let mut value = 0; return value = 3; }")
            .expect_err("assignment expression must be rejected");
        assert!(error
            .message
            .contains("assignment expressions have unit value"));
    }
}
